### ISSUE TITLE
Integrate Image Browser

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/ckeditor5#1]
Right now the image button only uploads a file from disk or accepts a URL. It should open the image browser and allow uploading or selecting an existing image.

**Comment by herbdool** [comment]
And also adding caption and alignment. In an other issue you mention enabling the image resize plugin. Is that an adequate replacement for the current entering of width and height? Maybe.

**Comment by indigoxela** [comment]
I really tried, but no progress. Giving up. Neither the 800+ lines of existing js code in backdrop-image.js (from Drupal?), nor the official CKE documentation re Plugin class help much to figure out, what's necessary to switch to Backdrop dialogs.

**Comment by quicksketch** [comment]
I'm trying to take a look at this again soon. The current Backdrop image plugin is based a lot on Drupal's image plugin, but we need to incorporate functionality more similar to the Drupal media plugin (which also opens a modal dialog). We'll end up with something the is the combination of both.

**Comment by indigoxela** [comment]
To clarify: _opening_ a Backdrop dialog from CKEditor isn't a problem. Here a simple example:

```js
class Experiment extends CKEditor5.core.Plugin {
  init() {
    const editor = this.editor;

    editor.ui.componentFactory.add( 'experiment', () => {
      // The button will be an instance of ButtonView.
      const button = new CKEditor5.ui.ButtonView();
      button.set( {
        label: 'Experiment',
        withText: true
      } );
      button.on( 'execute', () => {
        customTools.openDialog(editor);
      });
      return button;
    });
  }
}
```
... assuming that "customTools.openDialog" handles creating the dialog with settings and saveCallback. I have a dummy plugin, if that helps (probably not :wink:).

The way the code's currently constructed doesn't make things easy to understand (where to adapt, to *insert* an image with desired attributes). I'm aware that a lot of code is necessary only to handle the data-align and data-caption handling (which is possibly a Drupalism). But even without that... :shrug:

**Comment by quicksketch** [comment]
I filed a PR with my initial stab at this: https://github.com/backdrop-contrib/ckeditor5/pull/52

The PR swaps the behavior of the image button to open the Backdrop dialog directly (thanks @indigoxela I actually used your example to get started), and it can insert and edit an existing image. The alt text functionality combines pretty well with the out-of-box CKEditor alt text support: you can edit the alt text in the balloon editor and then also edit the image 

> And also adding caption and alignment.

The current `backdrop-image.js` plugin is a complete mess of Drupal copy/paste code, including a number of things that don't work (alignment, image styles, etc). We should probably separate out each of those problems into their own issues.

> The way the code's currently constructed doesn't make things easy to understand (where to adapt, to insert an image with desired attributes).

As for the overall structuring of the image plugin, I thought putting everything together would be easier than the separate-file approach. The `drupalMedia` CKEditor 5 plugin is over 30 separate files! But perhaps some separating would be beneficial. Or perhaps we can find better optimized ways of implementing things and the `backdropImage` plugin could be less than the 1000 lines it is now.

**Comment by indigoxela** [comment]
This is fantastic! :rocket: 

I tested inserting and editing images and updating alt text from both sides (dialog and CKE balloon). Works like a charm. :+1: And so does pasting images (if upload enabled), and the automatic data-file-id attribute.

> ... a number of things that don't work (alignment, image styles, etc). We should probably separate out each of those problems into their own issues.

Good idea, caption handling and alignment will be challenges on their own. The current PR is already a huge step forward.

Re width/height attributes (currently not set at all), I think there's some [movement on CKE-side](https://github.com/ckeditor/ckeditor5/issues?q=is%3Aissue+width+height+is%3Aclosed). So, fingers crossed, this task might get a little easier with a more current version.

**Comment by quicksketch** [comment]
Awesome, thanks for reviewing so quick @indigoxela! I didn't even try copy/paste yet, that's great that it still works.

I did some more cleanup to get the image button enabling/disabling in source mode, and highlighting in the "On" state when an image is selected. I went ahead and merged it since other work will need to build on top of the way attributes are passed around.
