### ISSUE TITLE
Update build process to include translations

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/ckeditor5#100]
The translations in this module are from v38 of CKEditor, while we're now running v41. We should update our build process to include assembling translations from all installed plugins into a single translation file per language.

**Comment by quicksketch** [comment]
I filed a PR at https://github.com/backdrop-contrib/ckeditor5/pull/102 to update our translations and the build script.

To recreate translations, follow the instructions in the UPGRADING.md file. The process is the same as before except now you copy both the `ckeditor-dll.js` file and the new `translations` directory into the module.

To test translations work:

- Enable Language and Locale module.
- Set up a second language such as German at `admin/config/regional/language`
- Visit `de/node/add/post`
- Confirm translations are used when hovering over Bold, Italic, etc.
- Confirm translations are also used with non-core plugins, such as "Source" and "Heading"
- The full list of translations can be verified by checking `window.CKEDITOR_TRANSLATIONS` in the console.

**Comment by indigoxela** [comment]
Right, our build process's still under construction.

At first I've been concerned, that simply concatenating the individual functions from plugin translation files wouldn't work, but they seem to do. :+1: Tested with the table plugin and others.

**Comment by quicksketch** [comment]
Yeah, I thought the same thing about concatenating the translations. The files are not as succinct as before, but the concatenated translation file seems to work just as well as if they were separately loaded. Short of a full webpack-based solution I think this suitable for making it so we can keep up-to-date with translations and releases.

**Comment by quicksketch** [comment]
Thanks @indigoxela again for reviewing. I can't understate how much I appreciate your help on this project. Thank you so much!

I merged https://github.com/backdrop-contrib/ckeditor5/pull/102 into 1.x-1.x.
