### ISSUE TITLE
Upgrade Path from CKEditor 4 to 5

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/ckeditor5#104]
What should an upgrade path look like when moving from CKEditor 4 to 5?

Right now, users enable CKEditor 5 module, then must reconfigure each text format if they want to transition from CKEditor 4 to 5.

Can we make this process easier? Should the process be manual or automatic?

I'm labeling this a feature request rather than a bug, since no data is lost without an upgrade path, and some sites may prefer to continue using CKEditor 4 for some period of time.

**Comment by quicksketch** [comment]
Some thoughts on possible approaches:

## Update.php / update hook

Probably not a good solution for this situation, since we don't want to force users to upgrade from CKEditor 4 just by running update.php (yet). Maybe that would be included when CKEditor 4 is entirely removed from core.

## Dedicated Update Form

We could add a message to the status report, and link to a dedicated form for converting text formats from CKEditor 4 to 5. This would be similar to the `utf8mb4` database update page, where it outlines the process and just has a single submit button, which converts all text formats currently using CKE4 to CKE5.

## Improve Toggle from CKE4 to 5 (and vice-versa?)

We could make it so that when an administrator reconfigures a text format (i.e. `admin/config/content/formats/filtered_html`) from CKE4 to CKE5, the configuration from CKE4 would transfer over to CKE5, such as the toolbar configuration and style list. This could be tricky, especially if we wanted to make it so that toolbar/config could be converted back from CKE5 to CKE4.

Other ideas?

**Comment by klonos** [comment]
I would be in favor of not blocking the merging of CKE5 into core because of this. The reason is that existing sites have the option to keep using CKE4 if switching to v5 turns out to be problematic for them, and for new vanilla sites, CKE5 will be the default. I am not saying to not provide an upgrade path - just that that should not be a blocker now. If we were at the same time removing CKE4 from core, then that would have been a different story.

So perhaps we have time to see if we can provide an upgrade path in 1.27.0, or then it'll need to wait till 1.28.0 or another future minor release.

My 2c.

**Comment by indigoxela** [comment]
> I would be in favor of not blocking the merging of CKE5 into core because of this.

@klonos I totally agree. :+1:

@quicksketch I think, it's too early to discuss update hooks, as we don't want to enforce anything, yet. We don't rip out v4, it's still there and still safe to use (unmaintained doesn't mean vulnerable).

However, a nice toggling experience is something to consider. The toolbar structure and the names of plugins are different between 4 and 5, but we might be able to "translate" between them. That doesn't appear trivial to me, though. And maybe it requires additions outside this module. Also tricky: plugins that aren't available for v5.

A message on the status page seems feasible and is - to my understanding - already prepared in core (in the ckeditor v4 module). It only needs to get updated (remove the contrib link...), as soon as v5 gets moved to core.

**Comment by olafgrabienski** [comment]
Both the update form and the toggle sound useful. The toggle when people want to test CKE5 before switching, or switch only some text formats, and the update form for an easy switch in situations where individual testing and selective switches aren't needed.

**Comment by quicksketch** [comment]
Another idea to simplify implementation: Build the conversion form, but allow updating one text format at a time. On the text format form itself, provide a link that jumps directly to the per-format conversion form. That would allow CKE4 -> 5 upgrades on a per-format basis. If you want to go back (for an advanced user), restore the config file for that format.

**Comment by quicksketch** [comment]
I filed an initial PR at https://github.com/backdrop-contrib/ckeditor5/pull/108.

It provides a message on any text format that uses CKE4:
![image](https://github.com/backdrop-contrib/ckeditor5/assets/100206/9841b155-05fe-4f59-a04b-0fab4fd20cef)

Taking you to the upgrade form:
![image](https://github.com/backdrop-contrib/ckeditor5/assets/100206/1f3c3152-7c8f-4652-830f-0b9622b6af3e)

And taking you back to the text format after the conversion:
![image](https://github.com/backdrop-contrib/ckeditor5/assets/100206/1959e0ad-8b57-4c3c-8319-9de3e7bb72e4)

It does not (yet) provide an option to convert all text formats at once, which might be nice if we're confident in the upgrade process. This is something that can be covered by SimpleTest as well.

**Comment by indigoxela** [comment]
I was curious to test things out...

TBH, I find it a bit irritating, that after running a procedure, I'm actually in an _open form_ (admin/config/content/formats/filtered_html), but the conversion has already happened in background (json file got updated).
What's the benefit of writing things to config, but sending people to the form?

I've been a bit nasty and added two plugins, that don't exist for CKE5 for my test run. Besides PHP nagging, it didn't feel very helpful to just throw the plugins out of the toolbar without any notice that it happened.

![cke4-before-setup](https://github.com/backdrop-contrib/ckeditor5/assets/842066/260ca0a5-0cc0-4ca2-bda0-75195d20aa9e)

We do know of missing plugins at some point, why not at least displaying their names? And if that happens, should it really be a (green) success message?

Here's the PHP nagging:

```
    Warning: Undefined array key "video_filter" in ckeditor5_upgrade_format() (line 1349 of ...modules/ckeditor5/ckeditor5.module).
    Warning: Undefined array key "Accordion" in ckeditor5_upgrade_format() (line 1349 of ...modules/ckeditor5/ckeditor5.module).
```

Another thought: it has already been [asked in the core issue queue](https://github.com/backdrop/backdrop-issues/issues/4122#issuecomment-1829820313), whether we'll support an additional text format for the new editor, while editing old content still loads v4. That's possible. But this upgrade procedure rather suggests, that we don't really want that sort of workaround, nor provide support for it.

**Comment by indigoxela** [comment]
Some info, why I chose these two unavailable plugins for testing:

- [Video Filter](https://backdropcms.org/project/video_filter) reports 146 active installs
- [CKEditor accordion](https://backdropcms.org/project/ckeditor_accordion) reports 77 active installs

Not huge numbers, but still significant.

**Comment by quicksketch** [comment]
>  What's the benefit of writing things to config, but sending people to the form?

My thinking here is that some site owners may prefer to bulk update all their text formats at once, so this sets up a process where we just need to loop over the text formats and the same process applies.

It might be better if we could not save the changes right away, but the text format form requires loading a saved format.

> But this upgrade procedure rather suggests, that we don't really want that sort of workaround, nor provide support for it.

I think that probably will be done by some sites: run two different editors depending on the need. But I think we'll probably want users to get off of the pseudo-unsupported CKEditor 4 as quickly as possible.

> We do know of missing plugins at some point, why not at least displaying their names?

Yeah, we could definitely improve this to warn users of dropped buttons. We can preview the conversion and put that on the confirmation form.

**Comment by quicksketch** [comment]
I pushed a commit to improve the confirmation form: Used the "danger-button" class like other confirmation forms, added a cancel link, and provided a message about buttons that will be removed:

![image](https://github.com/backdrop-contrib/ckeditor5/assets/100206/edc6dfe8-4f0c-4dfb-a5ba-384820146490)

Note there is not yet a change record so the link is a 404.

**Comment by indigoxela** [comment]
@quicksketch many thanks for the improvement, yes, buttons to remove now get displayed in the confirm step.

I've been a nasty tester again, and added an additional toolbar via admin UI to the CKE4 setting.

However, oops...
```
Warning: Undefined array key "toolbar" in ckeditor5_upgrade_format() (line 1348 of ...modules/ckeditor5/ckeditor5.module).
    TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in ckeditor5_upgrade_format() (line 1349 of ...modules/ckeditor5/ckeditor5.module).
count(): Argument #1 ($value) must be of type Countable|array, null given
```
Seems like something's broken now, probably unrelated to multiple toolbars.

**Comment by quicksketch** [comment]
I think that happens when you try to upgrade a text format that has already been upgraded. I'll add some checks to prevent upgrading text formats that aren't running CKEditor 4.

**Comment by indigoxela** [comment]
> I think that happens when you try to upgrade a text format that has already been upgraded.

That may be. I probably failed to flush caches between test runs, or did a page reload...
Now I get a nice "The text format Filtered HTML is already upgraded to CKEditor 5". :+1: 

BTW, it was a good idea to move the upgrade code to its own file. :+1: There's some phpcs nagging, but otherwise everything looks good.

**Comment by wimleers** [comment]
👋 

Interesting! 🤓 

It looks that for now, you've only ported the "button mapping" part from `\Drupal\ckeditor5\Plugin\CKEditor4To5UpgradePluginInterface::mapCKEditor4ToolbarButtonToCKEditor5ToolbarItem` in Drupal:
```
  $button_mapping = module_invoke_all('ckeditor5_upgrade_button_mapping');
```

The two parts that Drupal has in that interface, and Backdrop does not provide an equivalent API for:
- You kinda don't need `::computeCKEditor5PluginSubsetConfiguration()` if you're not trying to port the "automatically correctly configure `filter_html`" part from Drupal (which is _actually_ reliable, unlike what we built for CKEditor 4, but it does increase the API surface). But it _does_ configure some of the CKEditor 5 plugins based on the HTML allowed by `filter_html`, because some CKEditor 5 plugins now need more explicit configuration rather than automatically reacting to allowed HTML.
- But I _do_ think that you'd want the `::mapCKEditor4SettingsToCKEditor5Configuration()` part. See `\Drupal\ckeditor5\Plugin\CKEditor4To5Upgrade\Core::mapCKEditor4SettingsToCKEditor5Configuration()` — it automatically transforms the `StylesCombo` → `Style` settings (which is widely used in Drupal and I'm sure Backdrop too), and a number of contributed modules are using that API too.

I suspect that you're considering that trade-off and think these 2 are not worth it, because 90% of the value is in `Style` + `Heading` getting automatically configured, which you hardcoded:
```
  // Convert the styles list.
  if (!empty($format->editor_settings['plugins']['style']['style_list'])) {
    $style_list = $format->editor_settings['plugins']['style']['style_list'];
    foreach ($style_list as $style_item) {
      $format->editor_settings['style_list'][] = array(
        'name' => $style_item['name'],
        'element' => $style_item['element'],
        'classes' => explode('.', $style_item['attributes']['class']),
      );
    }
    unset($format->editor_settings['plugins']['style']);
  }

  // Create the heading list based on allowed HTML tags.
  if (!empty($format->filters['filter_html']->settings['allowed_html'])) {
    $tag_list = $format->filters['filter_html']->settings['allowed_html'];
    $tags = explode(' ', $tag_list);
    $new_tags = array();
    foreach ($tags as $tag) {
      $tag = str_replace(array('<', '>'), '', $tag);
      if (substr($tag, 0, 1) === 'h' && strlen($tag) === 2) {
        $new_tags[] = $tag;
      }
    }
    sort($new_tags);
    $format->editor_settings['headings'] = backdrop_map_assoc($new_tags);
  }
  else {
    $format->editor_settings['headings'] = array(
      'h1' => 'h1',
      'h2' => 'h2',
      'h3' => 'h3',
      'h4' => 'h4',
      'h5' => 'h5',
      'h6' => 'h6',
    );
  }
```

… or I guess you're assuming that it's then up to module authors to _really know what they're doing_ and provide fewer guardrails/guarantees than Drupal does, because you _do_ have:
```
  // Allow other modules to further modify the upgraded text format.
  backdrop_alter('ckeditor5_upgrade_format', $format, $original_format);
```

I think that can be an okay trade-off. 👍  Drupal had a _hard_ requirement to provide a reliable upgrade path. So it needed much more introspection, detailed validation, detailed test coverage. If you accept more sites upgrading from CKE4 to CKE5 having _not quite correct configuration_, then your current approach sure is preferable: it's less helpful to end users, but much simpler to maintain! 👍

**Comment by quicksketch** [comment]
Thanks for reviewing @wimleers! For the PR so far, I neglected to review what Drupal had done, so there really wasn't any decision making about what to port or not. I'll definitely review that file now, I can tell I missed a few things already (like using `table` instead of `insertTable` as the button name).

> or I guess you're assuming that it's then up to module authors to really know what they're doing and provide fewer guardrails/guarantees than Drupal does

Yes, the idea here is that contrib modules are given the entire text format configuration (which contains the editor configuration in Backdrop) and it's their job to update the configuration as needed. We could do something similar to Drupal for our API instead of an alter hook, but it's a lot more overhead. Backdrop doesn't have plugin system of D8+ so most APIs are hook-based. Because the text format and editor configuration are the same thing in Backdrop, just altering the text format provides the opportunity to make all modifications necessary in a single place.

>  If you accept more sites upgrading from CKE4 to CKE5 having not quite correct configuration, then your current approach sure is preferable

What configuration wouldn't be quite correct? Getting as close as possible to the CKE4 configuration is definitely the goal here. I think it can be achieved with the current API approach.

**Comment by quicksketch** [comment]
I updated the PR to include test coverage, including the conversion of all possible core CKEditor 4 buttons, with and without Filtered HTML enabled. It turned up a few bugs like headings not getting converted properly and missing the addition of the `<u>` tag to the filtered HTML list.

This seems pretty good to me as at least a starting point. The big gap I see in coverage is testing the added hooks.

**Comment by indigoxela** [comment]
The showBlocks.ShowBlocks plugin's now also available for conversion (#115).

The Maximize plugin's still pending (#76).

**Comment by quicksketch** [comment]
Thanks @indigoxela. I reviewed the state of the maximize issues and decided to move forward with what we have to get a suitable replacement in place. I merged the showBlocks PR too.

Now this upgrade process includes migrating both those plugins from CKE4 to 5. I finished the test coverage for the upgrade process, including coverage for the new hooks. I think this is ready to go, but I'd love an extra review.

**Comment by indigoxela** [comment]
I did a quick test: the upgrade seems to work smoothly now. :+1: 

This setup:

![cke4-settings](https://github.com/backdrop-contrib/ckeditor5/assets/842066/c1743bf8-eccd-4a23-8336-3dae37857736)

gets properly transformed to this setup:

![cke5-settings](https://github.com/backdrop-contrib/ckeditor5/assets/842066/07ec4ed6-5d1c-4dbc-9a26-88179aaa0ded)

And I get a proper warning re toolbar buttons to remove.

A minor glitch appears, though, when hitting the "Cancel" button on a multilingual site: the language prefix gets duplicated.
When I start on /de/admin/config/content/formats/filtered_html/ckeditor5-upgrade I end up on
**/de/**de/admin/config/content/formats/filtered_html - which is a 404, of course. Easy to fix.

**Comment by quicksketch** [comment]
Thanks so much for testing @indigoxela. I pushed one more commit to remove the unnecessary `url()` call, which was causing the double-prefixing.

**Comment by quicksketch** [comment]
I re-ran the upgrade a few more times locally and I think this is all ready too go. We can follow-up in further issues if there are any aspects that could be improved.
