### ISSUE TITLE
Vertical tabs add some (harmless) cruft to the settings JSON file

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/ckeditor5#105]
This module switched from regular fieldsets to vertical tabs, which is nice.

However, this adds a little cruft to the filter config:

```
        },
        "plugins": {
            "editor_settings__plugins__active_tab": ""
        }
```
We should filter that out on form submission.

**Comment by indigoxela** [comment]
The form construction is a bit ... odd, form items provided by the Filter module get restructured by this module, using the `'#parents'` property trick. The 'plugin' form submission's probably a side effect of that.

**Comment by quicksketch** [comment]
Excellent, thanks @indigoxela!
