### ISSUE TITLE
Move block indentation (p.indent1/2/3) functionality to contrib

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/ckeditor5#107]
CKEditor 5 uses indent1/indent2/indent3 classes when indenting content with indent / de-dent buttons. Backdrop does not currently provide any styling for these classes, despite it being the same classes that CKE4 used (apparently we did not make these buttons available in CKE4). Alternatively, we could remove the indent/de-dent buttons in the out-of-box buttons.

**Comment by indigoxela** [comment]
That's an interesting question... Indent/outdent in CKE is a context-sensitive thing.

For v4 the plugins for block and list indent/outdent are provided by a [contrib module](https://github.com/backdrop-contrib/ckeditor_indent/tree/1.x-1.x/plugins), v5 incorporated it in core, it seems. (Or, we did that...)

Now for the context:

The indent/outdent functionality is pretty useful for nested lists. Without it it's not really possible to create list nesting via UI.
It's however a bit odd with block content. Manual indent for div or any other block level element is hardly ever mobile-friendly. But as CKE probably won't let us limit the functionality to only lists, we might end up providing the styles. Not sure.

**Comment by quicksketch** [comment]
> For v4 the plugins for block and list indent/outdent are provided by a [contrib module](https://github.com/backdrop-contrib/ckeditor_indent/tree/1.x-1.x/plugins)

I did not realize that. It would be nice to have CKE5 support/migrate this functionality from the Backdrop contrib module if we're going to include the indent/de-dent buttons in core.

Weirdly, the `ckeditor.module` (v4) already includes this line to specify the indent classes:

```
'indentClasses' => array('indent1', 'indent2', 'indent3'),
```

But it does not include any kind of styling (nor buttons).

These are the same default indent classes as CKE5. Some users coming from Drupal 7 have reported a similar problem in D10 ([from this Slack thread](https://drupal.slack.com/archives/C01GWN3QYJD/p1701116452931019)).

**Comment by wimleers** [comment]
> These are the same default indent classes as CKE5. Some users coming from Drupal 7 have reported a similar problem in D10 ([from this Slack thread](https://drupal.slack.com/archives/C01GWN3QYJD/p1701116452931019)).

You beat me to it! 😄

**Comment by wimleers** [comment]
Also, interesting that you enabled the `IndentBlock` plugin out-of-the-box. Because CKEditor 4 in Drupal did _not_ do that.

**Comment by indigoxela** [comment]
We might be able to disable (or actually not load) the plugin in `function ckeditor5_get_config()`.

A simple `$config['removePlugins'] = array('IndentBlock');` seems to do the trick.
If we do that before calling backdrop_alter('ckeditor5_config'... a contrib or custom module would still be able to load and use it.

Do we want that?

The Backdrop module (ckeditor_indent) seems to enable it by default. People upgrading from 4 to 5 might miss functionality if we don't.
Or should we disable all indent plugins by default and leave enabling to contrib? It's part of our build.

**Comment by quicksketch** [comment]
Well just disabling the plugin would certainly solve the problem. I must have just assumed that we had indent/dedent enabled since the indent class list is present in our core `ckeditor.module`.

@indigoxela what do you think? Should we remove it from the build? Or is it a dependency for some other functionality?

Drupal 11 seems to include the plugin in the build but it's not actually enabled. The Drupal contrib project [ckeditor_indentblock](https://www.drupal.org/project/ckeditor_indentblock) simply enables it and adds a CSS file.

**Comment by olafgrabienski** [comment]
Not sure what exactly this issue is about: indentation for lists or in general? I think, for lists it's quite important to have the option.

**Comment by indigoxela** [comment]
> Not sure what exactly this issue is about

The current discussion is about IndentBlock - which adds CSS classes to block elements like paragraphs, which can then get styled as indented via CSS.

To my understanding we agree, that list indent (nesting of ul/ol) is a useful feature. We're not so sure about block elements.

**Comment by indigoxela** [comment]
> I must have just assumed that we had indent/dedent enabled since the indent class list is present in our core ckeditor.module.

Sure, it's enabled as it's declared as [plugin_dependency](https://github.com/backdrop-contrib/ckeditor5/blob/1.x-1.x/ckeditor5.module#L378).

We have several options now:

1. enable by default, but disable via removePlugins config (that makes it very easy for contrib to enable)
2. drop that dependency (but then it's useless without the List or DocumentList plugin)
3. switch that dependency to DocumentList (didn't test the builder behavior with that)

> what do you think? Should we remove it from the build?

That could make it harder for contrib to add it back, I guess.

I really like the feature for *lists*, but I'm no fan of the block indent feature. But that's really only a personal preference, no actual recommendation.

As the feature is on in the v4 module, we can't know, what people actually prefer (list / block). We can only assume. The only thing we currently know is, that there are [88 installs](https://backdropcms.org/project/usage/ckeditor_indent) - those people were able to find that plugin.

**Comment by indigoxela** [comment]
Here's my suggestion: https://github.com/backdrop-contrib/ckeditor5/pull/111

It switches the plugin_dependency from IndentBlock to DocumentList, which seems to make more sense to me.

Contrib can still enable the plugin (it's part of `@ckeditor/ckeditor5-indent` anyway). That shouldn't be too hard, as it can be done purely via hook_ckeditor5_config_alter (I think - didn't test).

**Comment by quicksketch** [comment]
Thanks @indigoxela, I think that should do perfectly for now. We'll leave the contrib module to handle indenting blocks if necessary.
