### ISSUE TITLE
DocumentList provides list-styles, but inline styles don't work in Backdrop

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/ckeditor5#109]
We're currently enabling the [DocumentList](https://github.com/backdrop-contrib/ckeditor5/blob/1.x-1.x/ckeditor5.module#L387) plugin in our setup. In addition to regular ol/ul this provides list-styles (roman, latin, square...) but as this requires inline-styles (I belief), these dropdowns are pointless for Backdrop. We don't allow inline-styles.

![list-styles](https://github.com/backdrop-contrib/ckeditor5/assets/842066/b79f835d-2f2d-48ac-931f-aec9c4e9ebed)

The easiest option would be to turn off the plugin that provides these extended settings.

Or implement a workaround to completely avoid inline-styles with that feature.

Fun fact: that's yet another topic, that also happened with TinyMCE, where I worked around it with parser/serializer, which is an equivalent to upcast/downcast conversion in CKE.

But as everything seems so much harder in CKE, maybe turning this off would be a lot easier. The functionality wasn't there with v4, so that might be OK.

**Comment by indigoxela** [comment]
It's a lot easier than expected, as these settings (in dropdown) get bundled in a sub-plugin, that's easy to disable - by simply not loading it. In the UI the dropdown vanishes, that's all. The buttons don't need any change.

We could still try to get that working without inline styles, but... :shrug:

**Comment by indigoxela** [comment]
A quick check in the plugin source code: it uses either inline styles or an (invalid for ul/ol) "type" attribute - both approaches don't work in B.

**Comment by quicksketch** [comment]
> In addition to regular ol/ul this provides list-styles (roman, latin, square...) but as this requires inline-styles (I belief)

Looks like `ul`, has a deprecated `type` attribute (though it still seems to work). But `ol` [seems to have supported attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol) for `type`, `start`, and `reversed`.

It'd be nice to be able to keep this little feature addition, but if needed we can remove it since you're right that CKE4 did not provide anything similar.

Our core themes (including Seven and Basis) demonstrate that none of our themes expect a `type` attribute. And they override it if it is provided. Perhaps we should disable the "type" attribute, since it is the most problematic. `reversed` and `start` don't seem to have any problems in my testing.

**Comment by indigoxela** [comment]
> Perhaps we should disable the "type" attribute, since it is the most problematic. reversed and start don't seem to have any problems in my testing.

So, only provide the "reversed" and "start" feature?

We can entirely turn off the inline styles / types. Interface ListPropertiesStyleConfig doesn't provide much to tweak OOTB. Not sure, how hard it would be to extend it. But if we'd like to provide a Backdrop Filter module compatible approach for list styles (ol and ul), it requires a bigger change.

Here's #112 for comparison.

![list-no-styles](https://github.com/backdrop-contrib/ckeditor5/assets/842066/fbd0b3c9-35e1-40a9-9c5f-e1a8efdee6f2)

The bullet list button has no dropdown anymore, the numbered list button has only the start and reversed setting.

**Comment by quicksketch** [comment]
Seems like a good compromise to me! PR looks good.

**Comment by quicksketch** [comment]
Thanks @indigoxela! I merged https://github.com/backdrop-contrib/ckeditor5/pull/112.

**Comment by indigoxela** [comment]
Strange... the dropdown (for ol) seems to be gone, although the PR has been merged.

What am I missing?

**Comment by indigoxela** [comment]
Some debugging:
```
document.getElementById('edit-body-und-0-value').ckeditor5AttachedEditor.plugins.get('DocumentListProperties').isEnabled

document.getElementById('edit-body-und-0-value').ckeditor5AttachedEditor.config.get('list').properties
```
The plugin's enabled, the settings are fine:
```
{
  "reversed": true,
  "startIndex": true,
  "styles": false
}
```
But no dropdown button, just a regular button for "ol".

We have a new build, with one additional plugin. But the version is the same. Can order matter in any way?

**Comment by indigoxela** [comment]
Wow, odd, if I enable the indent buttons (which declare a dependency on list.DocumentList), the dropdown appears all of a sudden. What's going on there?

**Comment by indigoxela** [comment]
Yes, it seeems to be related to plugin order...

If the indent buttons are enabled:
```
  "list.DocumentList",
  "list.DocumentListProperties",
```
^^ DocumentaList appears before DocumentListProperties in editorSettings.pluginList

If the indent buttons are off, or the dependency's removed:
```
  "list.DocumentListProperties",
// ... many other plugins, and then
  "list.DocumentList",
```
This potentially not only affects the list plugin. Should I open a fresh issue for plugin ordering and dependencies?

**Comment by quicksketch** [comment]
I ran into this issue [once before where CKEditor 5 does not seem to handle plugin loading order](https://github.com/ckeditor/ckeditor5/issues/11930#issuecomment-1762315263). The solution I used previously was to manually list the dependencies in the needed order rather than letting a dependency chain be assembled automatically.

**Comment by quicksketch** [comment]
@indigoxela I merged https://github.com/backdrop-contrib/ckeditor5/pull/119 that corrects the loading order. The previous behavior was correct in that we were indicating `list.DocumentListProperties` was a dependency of the `list.DocumentList` plugin. Loading the dependency before the plugin that depends on it would be correct; but it's actually the other way around in this case. We could separate out `list.DocumentListProperties` as a separately defined plugin, then used an enabled callback to determine if it should be loaded. But I think this easy solution in the PR is suitable; it gets the same result with less complexity.
