### ISSUE TITLE
Add showBlocks.ShowBlocks plugin

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/ckeditor5#115]
CKEditor 4 in Backdrop included a "Show Blocks" button out of the box. This same plugin exists for CKEditor 5 (`showBlocks.ShowBlocks`) but is not included in our current installation. We should bundle that into our install and expose the button (and upgrade it in #104).

**Comment by indigoxela** [comment]
Here we go, a [PR](https://github.com/backdrop-contrib/ckeditor5/pull/116) with a fresh build including the plugin.

I also took the liberty to remove some outdated files in the lib directory (/src, webpack.config.js...), left over from a standard build. But we can also do that in a different issue.

**Comment by indigoxela** [comment]
Re the lib/ckeditor5/LICENSE.md file - I realized that the license of our custom npm build is, in contrast, not MIT, but rather GNU General Public License Version 2 or later.

We probably should update that file, too.

But... some components have a different license. How to deal with that?

**Comment by quicksketch** [comment]
Super, feel free to merge if you're comfortable with it. Thanks!

**Comment by quicksketch** [comment]
Thanks @indigoxela!
