### ISSUE TITLE
[META] What needs to be done to move this module to core

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/ckeditor5#117]
What's the status of this module and at which point is it ready to get moved to core?

It seems like almost (#76) all the potentially blocking issues known from Drupal have been addressed (#36).
Or did new ones pop up?

The module still has bugs, but on the other hand, it might get more attention and testing, if it's integrated in core.

- Which issues do we want to be closed before moving?
- Which issues are OK to pull over to the core queue?
- Are there issues, that are OK to postpone?

**Comment by quicksketch** [comment]
> Which issues do we want to be closed before moving?

* https://github.com/backdrop-contrib/ckeditor5/issues/104

> Are there issues, that are OK to postpone?

* https://github.com/backdrop-contrib/ckeditor5/issues/18
* https://github.com/backdrop-contrib/ckeditor5/issues/97
* https://github.com/backdrop-contrib/ckeditor5/issues/113 (maybe? This might be easier once in core)

> Which issues are OK to pull over to the core queue?

Everything else should be pulled over to the core queue I think.

---

Other things: we should make a release that expresses a bit more confidence in its version number, i.e. `1.0.0`.

I started a blog post to describe the whole upgrade/transition process but I haven't finished it yet.

**Comment by quicksketch** [comment]
Blog post draft (unpublished): https://backdropcms.org/news/backdrop-cms-upgrade-from-ckeditor-4-to-5

**Comment by olafgrabienski** [comment]
Great to have an upcoming Blog post! Are there plans to publish it soon? Just read the post, looks great. Only suggestion: Make more clear in some text passages if they refer to the upcoming core version or to the contrib version of CKE 5. Also add a link to the contrib version.

**Comment by quicksketch** [comment]
Ah, sorry I meant to add links. I'll revise that tomorrow. Thanks @olafgrabienski! And I'll clarify as you suggest.

**Comment by quicksketch** [comment]
I added screenshots and published the blog post! https://backdropcms.org/news/upgrade-from-ckeditor-4-to-5

**Comment by quicksketch** [comment]
I considered making another `alpha`/`beta`/`RC` release, but after experiences of contrib modules that never reach a final version, I decided to make the jump to publish a stable version number. So I made it the 1.x-1.0.0 version, which is now released. https://github.com/backdrop-contrib/ckeditor5/releases/tag/1.x-1.0.0

Note we will still likely have additional releases 1.0.1, 1.0.2, etc.

**Comment by quicksketch** [comment]
Per https://github.com/backdrop/backdrop-issues/issues/4122, this module is now included in core! We did it!
