### ISSUE TITLE
Upgrade to CKEditor 40.2.0

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/ckeditor5#118]
Another minor release came out yesterday that includes a number of fixes and potentially a few API changes that might affect us.

https://github.com/ckeditor/ckeditor5/releases/tag/v40.2.0

**Comment by indigoxela** [comment]
Wow, they want to _deprecate_ DLL?

What they describe only adds concerns, and doesn't make anything easier for us. No clear description of alternatives (to come).

Does that mean, we have to rethink our current approach (which isn't ideal, but at least it works)?

And even more breaking changes to come in 2024? :face_with_head_bandage:

**Comment by quicksketch** [comment]
> Wow, they want to deprecate DLL?

Yeah, I am quite alarmed too. I posted as much here: https://github.com/ckeditor/ckeditor5/issues/15502#issuecomment-1852681392

They came back and said that loading individual plugins separately from the main bundle and being able to load plain-JS plugins were both goals and acknowledged that DLLs were commonly used. But yes, I forsee the approach breaking at some point, then you'll need to have two different forks of plugins. I'm super-annoyed at CKSource.

**Comment by indigoxela** [comment]
Anyway, here's a [PR](https://github.com/backdrop-contrib/ckeditor5/pull/121) with an update to 40.2.0.

None of the changes seem to affect us (neither image nor html-support). And all the bugs are still there. :shrug:

A little more testing would be nice, though.

**Comment by quicksketch** [comment]
Thanks so much @indigoxela. Seems to work well and I couldn't find any new issues. Indeed the linked image/caption issue (#69) persists, but everything seems good to me. I merged your PR. Thanks again!
