### ISSUE TITLE
CKEditor 5 RTL tests fail if CKEditor 4 is not enabled

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/ckeditor5#122]
Looks like our tests in `testRtlAdminIcons()` is actually checking for the presence of CKEditor 4 icons (.png), not the CKEditor 5 icons (.svg). I ran across this in core issue https://github.com/backdrop/backdrop-issues/issues/6340.

**Comment by indigoxela** [comment]
How long will this queue here stay relevant, now that cke5 is merged in core 1.x? Until 1.27.0 got released?

So, is our workflow to fix things here and to cherry-pick into core?

**Comment by quicksketch** [comment]
> How long will this queue here stay relevant, now that cke5 is merged in core 1.x? Until 1.27.0 got released?

Yeah, maybe give it a few months after release and we can come back here and set it up for being discontinued. We should probably update the README.md already with the fact this module is in core and won't be necessary post 1.27.0

> So, is our workflow to fix things here and to cherry-pick into core?

Generally, I think that sounds good.

**Comment by quicksketch** [comment]
I ported the change from the core tests in https://github.com/backdrop-contrib/ckeditor5/pull/124.
