### ISSUE TITLE
Save editor changes to prevent data loss on browser crash/reload/close

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/ckeditor5#22]
> The watchdog utility protects you from data loss in case the editor crashes. It saves your content just before the crash and creates a new instance of the editor with your content intact.

More details on how that feature works here: https://ckeditor.com/docs/ckeditor5/latest/features/watchdog.html

**Comment by quicksketch** [comment]
I'm not sure about automatically reattaching the editor when it crashes... seems like you might get into some kind of crash loop. Moreover, the editor crashing seems to be pretty rare (in my experience).

However, there is definitely some improvement we could do to help save a user's content. I notice with normal text areas or text fields, reloading the page does not loose in-progress form changes. But reloading with CKEditor attached looses changes to the field value (it will revert to the previous value if editing existing content).

- Visit `/node/add/page`
- Add a Title value.
- Add a few words to the body field with CKEditor 5 (or 4) attached.
- Hit the reload button or use Command + R.
- Note that the Title stays in place, but the body field is emptied.
- If switching to Full HTML (no editor), the body field maintains its value when reloading.

I'll look into if watchdog would help with this particular problem or if another solution is necessary.

**Comment by indigoxela** [comment]
Works like a charm. I compared behavior without patch (by making the textarea visible). The changes don't show up when editing content.

Then applied the patch, made textarea visible again, edited content and now I can see the changes also updated in the form field (with a small delay).

I'm in favor of this solution, as reattaching the editor really could lead to odd behavior.
TBH, I don't remember ever seeing an editor crash, but with this change we'd be prepared.

And the behavior when reloading is a real improvement.

**Comment by quicksketch** [comment]
Thanks for testing @indigoxela. This is probably good to go as-is, but I found that restoring the previous content is inconsistent across browsers. It works in Firefox, but only on reload (not session restore). Seems like Firefox has a hard time restoring the correct select list value for the text format, so sometimes CKEditor 5 doesn't get reattached like it should if it's not the default text format. There may be some additional work needed here or in core.

**Comment by klonos** [comment]
I started testing this with multiple instances of the editor in a single form, but need to take a break now. I'll return to it in a fews hours.

I took a look at the code, and it looks good, however my JS skills are not anywhere near being qualified to mark this as RTBC 🤷🏼

**Comment by klonos** [comment]
> - Visit `/node/add/page`
> - Add a Title value.
> - Add a few words to the body field with CKEditor 5 (or 4) attached.
> - Hit the reload button or use Command + R.
> - Note that the Title stays in place, but the body field is emptied.

Using Chrome (v118.0.5993.117 on MacOS if it matters), when I refresh the page, both fields get emptied for me, regardless of whether I am using CKE4 or 5, and regardless of whether I'm using v1.x-0.9.0-alpha4 with Backdrop 1.26.1 (demo sandbox on b.org), or the PR branch from @indigoxela's fork on my lando-based local with Backdrop 1.x 🤔 

Chrome is my main browser, so I have a few extensions that might be interfering, so I've also tested this on the following browsers:
- Firefox (v120.0 - no extensions): v1.x-0.9.0-alpha4 has the problem, whereas when I use the PR branch the issue is fixed.
- Safari (17.1 (19616.2.9.11.7) - no extensions): both v1.x-0.9.0-alpha4 and the PR branch have the problem (even the title field gets cleared). In fact, when testing in CKE4 and I refresh the page, the editor selection switches from CKE4 to the default CKE5 (so basically the choice of the editor is not remembered either)

I guess what I'm trying to say is that this does work, but it is browser-dependent.

After testing the above, using Firefox (since that was the only browser that would retain field values on refresh for me) I've added another multi-line text field in the page content type, and configured that to be non-plain, using filtered text, allowing all options (including CKE4 and CKE5). I then tried creating a page:
- added some text on the title field
- added some text in the CKE5 field
- switched the second field to CKE4 and added some text to it
- refreshed the page

What happened is that the text on the title field and the CKE5 field were retained, however the text was cleared in the CKE4 field (the CKE4 choice was remembered though 👍🏼 ).

I then changed the order of the fields, using CKE4 on the first, and CKE5 on the second. When I refreshed the page, the text in the title field and the CKE5 field was retained, while the text in the CKE4 field was lost.

I then removed the second text field from the page type, and I went to `admin/config/content/formats` and reordered the options, so that the CKE4 field comes before the CKE5 (effectively making the CKE4 option the default). I then tested this:
- added text to the title and body (CKE4) and refreshed the page -> text in the body field was lost
- added text to the title and body field, and switched to CKE5, then refreshed -> text field in body field was retained

**Comment by indigoxela** [comment]
Maybe we should split this issue into "regular updates in the textarea" and "advanced crash/reload handling"? The latter as follow-up?

**Comment by quicksketch** [comment]
I don't think there's any harm in the current PR. It definitely seems to help in some situations. I could also see it being beneficial for modules that try to provide auto-saving ability. This module probably can't go much further to persist values by itself; if browsers do not repopulate current values, a more comprehensive solution would be needed for the entire form.
