### ISSUE TITLE
Enable ImageResize plugin

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/ckeditor5#24]
Enable the ImageResize plugin so that images can be resized with a drag handle.

https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imageresize-ImageResize.html

Also be sure to use px instead of the default % resize option: https://www.drupal.org/project/drupal/issues/3348603

**Comment by quicksketch** [comment]
I enabled ImageResize in https://github.com/backdrop-contrib/ckeditor5/pull/52 and set to use px. The image height/width isn't getting passed to the dialog yet though.

Also @indigoxela noted in #1 that CKEditor's core support for height/width is getting better:

> Re width/height attributes (currently not set at all), I think there's some [movement on CKE-side](https://github.com/ckeditor/ckeditor5/issues?q=is%3Aissue+width+height+is%3Aclosed). So, fingers crossed, this task might get a little easier with a more current version.

We should update to get some of those latest fixes.

**Comment by quicksketch** [comment]
Version 40 was released last week that includes the height/width fixes: https://github.com/ckeditor/ckeditor5/releases/tag/v40.0.0

**Comment by indigoxela** [comment]
The image resize plugin works... sort of. :wink:

When inserting the image, it now gets wrapped in a "figure" element with inline styles for width (no height) with an empty value. This results in small images blown up to full width, which makes them blurry. Anyway, yet another step forward, as the resize handles are there and functional. :+1:

**Comment by quicksketch** [comment]
Thanks @indigoxela. I'm working on alignment (#53) right now, if you're at all interested in tackling this or updating to v40.0.0 (no separate issue, but it could be done here) that would be a great help.

**Comment by indigoxela** [comment]
Re updating CKE version ... I have questions.

Until after npm install - all clear. But then "Save the final file as ckeditor.js" - where should I put it? And does the name have to be exactly "ckeditor.js"? I'm asking that, because the name (same as v4) caused a problem for CKE4 mis-guessing its own root and required a workaround (see also #43). Oh - and does the order of collecting play any role?

At which point of the steps do translation files get collected? Manually or by building? How about the map file? Is that up-to-date after building? (Obviously I'm not familiar with the webpack workflow.)
Does enabling ImageResize require additional steps when building?

**Comment by quicksketch** [comment]
> "Save the final file as ckeditor.js" - where should I put it? And does the name have to be exactly "ckeditor.js"?  I'm asking that, because the name (same as v4) caused a problem for CKE4 mis-guessing its own root and required a workaround

Oh hm. I hadn't realized that. Right now the ckeditor5.module expects it to be named ckeditor.js in `ckeditor5_library_info()`, but renaming it to `ckeditor5.js` or `ckeditor-dll.js` is a good idea.

> Oh - and does the order of collecting play any role?

I started with the `ckeditor-dll.js` file, and then I added all other files alphabetically.

> At which point of the steps do translation files get collected?

Oh this is a good point that is not in the README.md. The current translations came from assembling a build through the UI at https://ckeditor.com/ckeditor-5/online-builder/ My first attempts used the online builder but that packaged the plugins in a way that is non-extensible. So the translations were from the online builder while the concatenated file was from `npm install`. Yes this is suuuper messy. :frowning_face: 

> How about the map file? Is that up-to-date after building? (Obviously I'm not familiar with the webpack workflow.)

The map file is not up-to-date and does not work at all.

>  Does enabling ImageResize require additional steps when building?

No, it's included as part of the `@ckeditor/ckeditor5-image` npm package.

I'm not familiar with webpack either. I think that's the likely long-term solution though, that we use webpack to assemble both the concatenated build and the translations. You probably already found the referenced issue over at https://github.com/ckeditor/ckeditor5/issues/10142 that was referenced in the `UPGRADING.md` file.

**Comment by indigoxela** [comment]
I think, we can close this issue, as resizing definitely works now.

**Comment by quicksketch** [comment]
I made an additional commit directly to 1.x-1.x to fix an issue with updating to CKEditor 40.0.0. The height/width values now set by CKEditor are integers rather than strings, so calling `data.attributeNewValue.replace('px', '')` on an integer was throwing an error since you can't run `.replace()` on an integer.

**Comment by indigoxela** [comment]
Yeah, v40 definitely does some things completely differently. Will test soon.
