### ISSUE TITLE
Integrate Generic HTML Support for Backwards-Compatibility

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/ckeditor5#28]
The [Generic HTML Support](https://ckeditor.com/docs/ckeditor5/latest/features/html/general-html-support.html) plugin provides support for tags that are otherwise unsupported by CKEditor. For example CKEditor doesn't know how to handle a generic `<div>`, `<span>`, or `<cite>` elements, as well as any arbitrary attributes like `style` or `id`.

For backwards-compatibility with existing content, CKEditor 5 module should allow a pretty wide-ranging set of attributes and tags, based on the filter configuration (if the tag filter is enabled).

**Comment by indigoxela** [comment]
Seems like the `<div>` and `<span>` work just fine. (After adding manually in source mode.) They persist and text wrapped in them is editable.

However, the dl/dt/dd tags get replaced with paragraphs. Even when saving in source mode. Is this officially documented behavior?

To test, simply copy the example from [official documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl)

**Comment by indigoxela** [comment]
Here's a PR, WIP and stuffed with "todo" and question marks. :wink: #39

The good thing: we can prevent data loss by adding the tags from existing filter settings to `htmlSupport->allow`, so the editor won't throw them out from existing content.

Testing is tricky, though. I ended up with temporarily hardcoding stuff in function ckeditor5_get_acf_settings(), just to see, how the editor behaves.

```
  $html_restrictions['allowed']['footer'] = array(
    'attributes' => array(
      'data-foobar' => TRUE,// Anything.
      'onclick' => 'foobar',// Just this value.
      'data-other' => FALSE,// The default.
    ),
    'class' => array(
      'myclass',
      'otherclass',
    ),
    'style' => array(
      'color' => 'green',// Just this color.
      'font-size' => TRUE,// Every value.
    ),
  );
```
:point_up_2: This works fine in the editor, but I'm not sure, how this is supposed to get set on Backdrop (module) side.

**Comment by indigoxela** [comment]
Another note: I had to add unrelated changes in ckeditor5.module, to prevent a fatal and lots of nagging on PHP 8.1. Still investigating.

**Comment by indigoxela** [comment]
Although there are still `@todo` comments, testing makes sense. Probably I won't get any further.

**Comment by argiepiano** [comment]
@indigoxela, thanks for all this work. I wanted to try a bit of testing. 

1. Installed the module and enabled
2. Changed the editor for filtered text 👍🏽 
3. When I go to the node creation form that includes Body (Filtered Text), there is a JS error that prevents me to test anything (in fact it also stops JS on its tracks, and kills the admin bar and every JS script on the site).

<img width="1253" alt="Screen Shot 2023-08-20 at 8 08 32 AM" src="https://github.com/backdrop-contrib/ckeditor5/assets/9938978/73bfe993-0673-44f5-acde-83c783c21f6a">

Is there a way to avoid this to try some testing?

**Comment by argiepiano** [comment]
Also getting the error reported in #38 (even after the patch), when I revisit the Filtered Text settings UI.

**Comment by indigoxela** [comment]
Yeah, switching an existing format is still too fragile, I guess. In your case the image caption seems to interfere.

I created a new filter on my testing site, to get that working. Important: switch the original one back to cke4, save, flush caches.

**Comment by argiepiano** [comment]
Thanks. I create a new text format. Can you give me a few pointers of what I should be testing/looking for? I tried the `dl/dt/dd` tags and they are preserved as long as I list them in the "Limit allowed HTML tags".

**Comment by indigoxela** [comment]
> I tried the dl/dt/dd tags and they are preserved as long as I list them in the "Limit allowed HTML tags".

That's one of the key points. Tags for which CKE has no plugin registered, but are allowed by the filter settings should not get replaced or removed. That would happen, if we don't use the 'htmlSupport' feature/setting.

For more detailed testing, like custom attribute settings, you'll need a (small) custom module, that implements hook_ckeditor5_config_alter(). Or eventually hook_filter_info_alter() to switch the 'allowed html callback' callback...

**Comment by argiepiano** [comment]
One thing I noticed:
1. I added the tag `<nonsense>` to the list of allowed HTML tags
2. Created  a node. Switched to `Source` in CKEditor5
3. Entered the following:
```html
<nonsense>Nothing!</nonsense>
<p>Hello!</p>
```
4. Saved
5. Edited the node, switched to `Source`. Now I see the following:

```html
<nonsense>Something</nonsense>
<p>&nbsp;</p>

<p>Hello!</p>
```
The more I re-save, the more `<p>&nbsp;</p>` are added. Also switching back and forth between the Source and WYSIWYG keeps adding these.

**Comment by indigoxela** [comment]
> `<p>&nbsp;</p>`

Or, wait, which filters do you have turned on for your format? Is "Convert line breaks into HTML" still enabled?

**Comment by argiepiano** [comment]
> Is "Convert line breaks into HTML" still enabled?

No.

<img width="1199" alt="Screen Shot 2023-08-20 at 8 47 24 AM" src="https://github.com/backdrop-contrib/ckeditor5/assets/9938978/a1c96cb7-b26e-4797-a750-34691daeabcc">

**Comment by indigoxela** [comment]
Here's a quick and dirty module, that enables attributes via admin UI. Not ready yet... just to play with it.

<details>
<summary>foobar.module</summary>
```
/**
 * Implements hook_filter_info_alter().
 */
function foobar_filter_info_alter(&$info) {
  if (isset($info['filter_html'])) {
    $info['filter_html']['allowed html callback'] = 'foobar_filter_allowed_html';
  }
}

/**
 * Custom callback for more fine granular settings via filter admin UI.
 */
function foobar_filter_allowed_html($filter, $format) {
  $restrictions = array('allowed' => array());
  $tags = preg_split('/\s*<|>/', $filter->settings['allowed_html'], -1, PREG_SPLIT_NO_EMPTY);

  foreach ($tags as $tag) {
    if (strpos($tag, ' ') === FALSE) {
      $restrictions['allowed'][$tag] = TRUE;
      continue;
    }

    $parts = preg_split('/\s+/', $tag);// Not if value contains space.
    $tag = array_shift($parts);
    $restrictions['allowed'][$tag] = array();
    foreach ($parts as $attrib) {
      if ($attrib == 'style' || substr($attrib, 0, 2) == 'on') {
        continue;
      }

      if (strpos($attrib, '=') !== FALSE) {
        list($key, $value) = explode('=', $attrib);
        // Multivalue has spaces... too complicated.
        $restrictions['allowed'][$tag][$key] = TRUE;
        continue;
      }

      $restrictions['allowed'][$tag][$attrib] = TRUE;
    }
  }
  //debug($restrictions);

  // The 'style' and 'on*' ('onClick' etc.) attributes are always forbidden.
  $restrictions['allowed']['*'] = array('style' => FALSE, 'on*' => FALSE);
  return $restrictions;
}

```
</details>

**Comment by indigoxela** [comment]
Strange, the "paragraph mystery" doesn't seem to happen here.

**Comment by argiepiano** [comment]
Regarding the "paragraph mystery": for some reason I was still using CKEditor 4 - which added those &nbsp;. Sorry about the false alarm!

However, I'm testing again, this time making sure I have CKE5. The custom tag `<nonsense>` gets replaced by `<p>` and is not preserved despite it being added to the list.

<img width="1192" alt="Screen Shot 2023-08-20 at 9 13 31 AM" src="https://github.com/backdrop-contrib/ckeditor5/assets/9938978/baa0aa41-ecbb-4530-b8ac-323231ae2961">

When creating:
<img width="1221" alt="Screen Shot 2023-08-20 at 9 13 55 AM" src="https://github.com/backdrop-contrib/ckeditor5/assets/9938978/d92432a4-52e3-40ef-af6a-4b0e68fcc09e">

Saved and editing:
<img width="1235" alt="Screen Shot 2023-08-20 at 9 14 06 AM" src="https://github.com/backdrop-contrib/ckeditor5/assets/9938978/0c92f811-fa77-4021-a34e-54e9918a408d">

**Comment by indigoxela** [comment]
Yep... now we have the same result (nonsense getting replaced).

I get good results with.
```
<footer> <section> <sub> <sup> <dl> <dt> <dd> <code> <pre> <hr>
```
Also toggling h2 on/off works as expected.

I'm not sure, what exactly CKE checks, 1.3MB minified js isn't ideal for debugging/recherche. :laughing:

**Comment by argiepiano** [comment]
> I'm not sure, what exactly CKE checks, 1.3MB minified js isn't ideal for debugging/recherche.

So, this is probably a problem with CKE5, and not the way the limit html tags info is passed to the GHMTLS plugin?

**Comment by argiepiano** [comment]
> I get good results with.
<footer> <section> <sub> <sup> <dl> <dt> <dd> <code> <pre> <hr>

I'm now testing with `<pre>` but it still gets replaced. Clear caches and triple-checked I'm using CKE5

<img width="1206" alt="Screen Shot 2023-08-20 at 9 38 54 AM" src="https://github.com/backdrop-contrib/ckeditor5/assets/9938978/aaaa0510-3d42-4d35-bcc7-ae2c88a73f9b">

Creating:
<img width="786" alt="Screen Shot 2023-08-20 at 9 38 10 AM" src="https://github.com/backdrop-contrib/ckeditor5/assets/9938978/47850b6b-6e00-4f5e-87ce-7529a831abc7">

Editing:
<img width="766" alt="Screen Shot 2023-08-20 at 9 38 19 AM" src="https://github.com/backdrop-contrib/ckeditor5/assets/9938978/aaebe823-be62-4f32-9fc1-436b102451a0">

**Comment by indigoxela** [comment]
> So, this is probably a problem with CKE5, and not the way the limit html tags info is passed to the GHMTLS plugin?

I can tell you for sure, that... I have no idea. Valid (existing) HTML tags seem to work (block level and inline).

But even if I add some definition via foobar_filter_allowed_html() for `<nonexistent>`, that gets replaced with paragraphs.
Although the def gets through to CKE (checked via debug in foobar_ckeditor5_config_alter()). It's rather CKE, so testing with actually valid tags seems better.

**Comment by indigoxela** [comment]
Another finding on my side: make sure, you turn on browser developer tools, and prevent client-side caching. Browser cache's a constant source of false failures.

**Comment by argiepiano** [comment]
Thanks. Disabled browser caching, but `<pre>` is still replaced by `<p>`. I will put this to rest for the rest of the day, but will come back during the week. Thanks for all the work.

**Comment by indigoxela** [comment]
Sure, your testing's always welcome. We wont get everything running today, anyway. :wink: (And I need a pause, too.)

**Comment by indigoxela** [comment]
> To test this PR, do I need more than to apply the PR, e.g. install a custom module?

@olafgrabienski More detailed steps, as it isn't as smooth, yet:

- Install the ckeditor5 module, latest dev
- Apply the patch from this PR
- Create a NEW filter (do not use "Filtered HTML" - switching isn't working well)
- Reorder filters to get your new filter on top (/admin/config/content/formats)
- Create a new node, make sure, the right editor is loaded
- Ignore some console nagging - as long as the editor initializes, yay!
- If something's still flaky, flush caches in B
- Make sure, you don't run into trouble with browser caching
- Also don't forget to turn off js aggregation

The new filter should have CKEditor5 set. And no other filters (e.g. image stuff interferes). It might be necessary to save the filter settings, and open the form again. At least, I had some trouble. But then, things should be ready for actual testing.

**Comment by indigoxela** [comment]
Had a quick idea, how to get regexp pattern for `on*` attribs working – in ckeditor5.js, and that's where I added it (experimental).

**Comment by olafgrabienski** [comment]
@indigoxela Thanks for the instructions! I followed the steps and tested the `<pre>` tag again: Switched to Source mode, put `<pre>Hello, world.</pre>` in the text area and switched back. As a result, the `<pre>` tag was removed (more precisely: replaced by a paragraph).

Interesting: when I insert a code block using the appropriate toolbar icon, CKEditor itself makes use of the `<pre>` tag, resulting in the following code:

```
<pre><code class="language-plaintext">Hello, world.</code></pre>
```

With this code, the Editor mode can be switched, and CKE5 doesn't remove anything.

**Comment by argiepiano** [comment]
Like I reported yesterday, and like @olafgrabienski reported today, even after patching the module, flushing caches, adding the "pre" to the list of allowed tags, and preventing the browser from caching, (and flushing caches compulsively)  "pre" (and any other tag added to the list) gets removed . @indigoxela, this doesn't seem to happen on your end, and I wonder why. There must be something you are doing that we are not.

**Comment by olafgrabienski** [comment]
> The "pre" tag should get replaced, as long as "pre" isn't part of the setting "Limit allowed HTML tags".

Sorry, I wasn't clear about that: I added `<pre>` to the allowed HTML tags right away, when I set up the new text format for CKE 5.

**Comment by indigoxela** [comment]
How weird is that? It only works, when I add a custom style. :zany_face: 

In the style list on /admin/config/content/formats/MYFORMAT I added:
```
div.box|a div box with class
span.huhu|a span with class
```
And added the styles button to the toolbar - and then it works.
If I remove the styles button, each and every markup gets replaced with `p`. If I put the styles button back, things work again. Don't ask me, what's going on.

**Comment by olafgrabienski** [comment]
> How weird is that? ...

Indeed! Confirming. As soon as I add the Styles button to the Editor toolbar, formerly allowed `<pre>` tags work without problem. Even if I don't define a style in the related Style list.

**Comment by indigoxela** [comment]
We have to load this plugin! Currently it's only loaded, if required by another CKE plugin. :bulb: 

Fixed by latest commit. Pew...

**Comment by olafgrabienski** [comment]
> We have to load this plugin! (...) Fixed by latest commit.

Great, that works for me! I've added the latest change and removed the Styles button, and `<pre>` tags continue to work. Other (allowed) tags like those for definition lists work as well.

**Comment by indigoxela** [comment]
After merging #40, I had to resolve a merge conflict, when rebasing this one. And now I'd appreciate additional testing. Switching should work now.

**Comment by olafgrabienski** [comment]
> now I'd appreciate additional testing. Switching should work now.

@indigoxela After downloading the latest commits and applying the PR here, I was still able to use `<pre>` tags and definition lists with CKE 5. I've also switched the following content from the old CKE powered text format "Filtered HTML" to a CKE 5 powered format, without any problem.

```
<h3>This is a heading</h3>

<pre>
Hello, here comes some pre text.</pre>

<p>And here some <code>code text</code>.</p>

<p>A definition list (example from developer.mozilla.org/en-US/docs/Web/HTML/Element/dl):</p>

<dl>
	<dt>Beast of Bodmin</dt>
	<dd>A large feline inhabiting Bodmin Moor.</dd>
	<dt>Morgawr</dt>
	<dd>A sea serpent.</dd>
	<dt>Owlman</dt>
	<dd>A giant owl-like creature.</dd>
</dl>

<p>And now to something completely different: Lorem ipsum dolor ...</p>
```

**Comment by indigoxela** [comment]
Some more merge conflicts today. Things still seem to work, but testing's appreciated. :pray:

**Comment by indigoxela** [comment]
@quicksketch I think, I found a way to let CKE5 behave like CKE4. This really needs review, though, so I won't attempt to merge on my own.

@olafgrabienski or @argiepiano testing would be great, if your time permits. For example, compare 4 and 5 with "Limit allowed HTML tags" filter turned on and off in the format.

**Comment by olafgrabienski** [comment]
@indigoxela Thanks for the update! Based on the current PR, I've repeated my [testing from last week](https://github.com/backdrop-contrib/ckeditor5/issues/28#issuecomment-1709788383), with the same results: works fine!

Apart from that, I've also added a tag to the allowed HTML tags, and tested results in both editors. Finally, I've disabled and re-enabled the "Limit allowed HTML tags" filter. Both CKE 4 and 5 behaved the same in the various situations.

**Comment by quicksketch** [comment]
@indigoxela The PR makes a ton of progress getting CKE4 and 5 to treat the same HTML the same! It works very well in my testing. I did find that _editing_ unsupported markup can have some unexpected results. In particular if deleting within an unsupported tag, sometimes CKE5 will merge the content with the previous tag. But I think expecting CKE5 to work well with unexpected markup might be asking too much. It's enough to get to the point where loading CKE5 on CKE4 content doesn't mangle the markup just by looking at it.

Separate from Generic HTML Support, I found that there are some other issues with CKE4-to-5 content due to CKE5's automatic conversion of some tags.

For example copy/pasting super text from Google Docs results in this markup when pasting into CKE4 (with the HTML Tag Filter entirely off):

```
<p><span style="vertical-align:super;">Hello from Google Docs</span></p>
```

But even with identical configuration and no HTML filtering applied, switching this same content to CKE5 results in it converting the HTML to:

```
<p><sup>Hello from Google Docs</sup></p>
```

Because CSS is different between `<span style="vertical-align:super;">` and `<sup>`, it results in visual differences.

Overall, this isn't _directly_ related to Generic HTML Support, but it is related to maintaining unmodified markup between CKE4/5. It's caused by CKE5's automatic upcasting of certain tags. Other tags also get automatically converted like `<strike>` to `<del>`, and `<span style="text-decoration:underline">` to `<u>`.

I'm not sure if these changes need to be addressed at all, and probably not a part of this particular issue.

**Comment by quicksketch** [comment]
I also left a few comments in the PR: https://github.com/backdrop-contrib/ckeditor5/pull/39 for some code suggestions (very minor).

**Comment by indigoxela** [comment]
> I also left a few comments in the PR

@quicksketch Many thanks for having a look :pray: , I've tried to address your comments.

While testing again, I found a deprecation notice in console logs: `matcher-pattern-deprecated-attributes-class-key Object { class: true }`. No clue yet, what triggers this, as we use the proper "classes" key in ckeditor5_get_generic_html_settings(). :shrug:

**Comment by quicksketch** [comment]
Thanks @indigoxela, is that error caused by the PR?

**Comment by indigoxela** [comment]
> is that error caused by the PR?

@quicksketch actually not (could have checked that before :wink: ). Will check, if one of the plugins (toolbar) causes it...

Edit: Ha! The backdroplink plugin seems to cause it. So it's unrelated here.

**Comment by quicksketch** [comment]
Awesome, in that case let's merge this and move forward. Great work @indigoxela!
