### ISSUE TITLE
Keyboard navigation of toolbar configuration

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/ckeditor5#31]
I have created https://github.com/backdrop/backdrop-issues/issues/6159 as a core a11y issue. Perhaps we want to work on that feature here, or leave it for the core queue once the module has been moved into core.

We should consider whether the code to implement this feature can be abstracted and shared between v4 and v5.

**Comment by quicksketch** [comment]
I thought this was going to be a lot of work but it wasn't too bad. I filed a PR at https://github.com/backdrop-contrib/ckeditor5/pull/92 that adds arrow key support to arranging buttons. If you have the chance to test that would be amazing @klonos.

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop-contrib/ckeditor5/pull/92. Please open a new issue for any follow-ups. Thanks @klonos!
