### ISSUE TITLE
Provide warning when CKEditor5 modifies content just by being used on a field

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/ckeditor5#37]
CKEditor 5 can sometimes modify the source code of content. Even with Generic HTML Support, the editor will make changes to "fix" the content, such as wrapping root-level text in `<p>` tags.

As an extra precaution, we'd like to make it so that CKEditor provides a warning if the content is going to be modified _just by viewing_ the content in the editor.

**Comment by quicksketch** [comment]
I filed a PR for this at https://github.com/backdrop-contrib/ckeditor5/pull/75.

* In order compare before and after attach values, I needed a way to make the whitespace consistent. Comparing strings or using [`element.isEqualNode()`](https://developer.mozilla.org/en-US/docs/Web/API/Node/isEqualNode), both take into account whitespace. Since CKEditor [does not pretty-print its saved source](https://github.com/ckeditor/ckeditor5/issues/8668), I ported the formatter used when you click "view source". That formatter is used when comparing values.
* The editor also now uses this formatter when saving the value into the field on save.
* If the value is modified by the act of attachment, the editor is disabled and a warning message is attached instead. Clicking on the link within the banner will load the editor.

![image](https://github.com/backdrop-contrib/ckeditor5/assets/100206/ee211a2e-a0a0-4502-b8b1-abb0469a57c0)

This approach makes it so that other fields can be modified on existing content without worrying about what CKEditor will do to the body content.

To test:

* Add CKEditor 5 to a text format, while leaving another text format with CKEditor 4 or no editor at all.
* Create a node. Switch to "Raw HTML" and add some text in the root, without a wrapping tag like `<p>`.
* Switch to the text format with CKEditor 5. The warning will be shown, and the text will not be modified.
* Enable the editor with the link in the warning.
* Switch back to "Raw HTML" and check the markup changes.

**Comment by indigoxela** [comment]
Not sure, if I'm testing correctly, but this is what I did

- Two formats, CKE4 and CKE5
- The format with 4 allows details/summary, the one with 5 does not (is this expected testing?)
- Add details/summary element with 4 (source code) and save
- Open again (still 4), now try to switch to 5
- I get the warning, and the editor doesn't automatically initialize :+1: (enabling the editor eliminates the details element by converting to "p")

Works for me!

As we have GHS in place, the whole situation with switching is less dangerous, but still a little oversight in the setup of "Limit allowed HTML tags" could lead to data loss, so this warning totally makes sense.

**Comment by olafgrabienski** [comment]
> (...) a little oversight in the setup of "Limit allowed HTML tags" could lead to data loss, so this warning totally makes sense.

I agree! As the focus of the issue wasn't text filter configuration from the beginning, I'm wondering if we should improve the warning text to take that into account. At the moment, the text says to "Review content carefully after activating", and it doesn't give a hint to text filter configuration.

**Comment by quicksketch** [comment]
I went ahead and merged https://github.com/backdrop-contrib/ckeditor5/pull/75. Even if we reword the message or change how it works, the PR adds useful functionality, including formatting the HTML source.

**Comment by quicksketch** [comment]
I made a follow-up commit at https://github.com/backdrop-contrib/ckeditor5/pull/81 to fix the warning from showing up even when no changes were actually made, and to save the formatted HTML to the database.
