### ISSUE TITLE
Get some obvious tasks done

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/ckeditor5#44]
While waiting for discussion on my other PR, I could fix some other things here:

- Add LICENSE.txt
- Fix code display on GH
- Enable running functional tests on PRs
- Switch main branch from main to 1.x-1.x
- Fix dependency declaration
- Do not use BACKDROP_VERSION constant in module

**Comment by quicksketch** [comment]
Absolutely, go for it! You may have notice I pushed a release (`1.x-0.8.0-alpha1`) that was just to get a project page up on backdropcms.org so we could link to it from Backdrop core 1.26.0.

I'm not sure we're ready for running functional tests yet, they're not updated or passing. But commenting them out and getting the contrib module going running the tests would be great.
