### ISSUE TITLE
Property extraAttributes in hook_ckeditor5_plugins can cause deprecation nagging, if "class" is set

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/ckeditor5#49]
Example: `$plugins['link.Link']`

It sets:

```
      'backdropLink' => array(
        // Specify an array of CKEditor model name => attribute name values.
        // These attributes are then allowed to be changed via the Backdrop
        // link dialog. Additional attributes can be added here to prevent
        // CKEditor from striping out attributes on anchor tags.
        'extraAttributes' => array(
          'linkTarget' => 'target',
          'linkClass' => 'class',
          'linkTitle' => 'title',
          'linkId' => 'id',
          'linkRel' => 'rel',
          'linkDataFileId' => 'data-file-id',
        ),
      ),
```

Note the "linkClass" line. That leads to following console warning:

```
matcher-pattern-deprecated-attributes-class-key 
Object { class: true }
 
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-matcher-pattern-deprecated-attributes-class-key
```

Commenting out the linkClass line, makes the warning go away.

This has changed in v29.1:

> Starting from v29.1.0, the [Matcher](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_matcher-Matcher.html) feature deprecated matching style and class HTML attributes using attributes key-value pairs pattern.

No indication, when this gets removed, though.

**Comment by quicksketch** [comment]
Thanks @indigoxela for filing this issue. I believe I have fixed the problem in https://github.com/backdrop-contrib/ckeditor5/pull/74.

There seems to only be one place where this error occurs, so rather than refactoring classes to be special everywhere, I only added this one exception.

**Comment by indigoxela** [comment]
Perfect! I applied the patch and now there's silence in the console. :+1:

**Comment by quicksketch** [comment]
Excellent, thanks @indigoxela! I merged https://github.com/backdrop-contrib/ckeditor5/pull/74.
