### ISSUE TITLE
False "CKEditor is installed but not enabled on any formats." warning in the status report

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/ckeditor5#50]
I just installed a fresh copy of Backdrop 1.x + the latest 1.x branch of this module, and saw this in the status report:
![image](https://github.com/backdrop/backdrop-issues/assets/2423362/0205fc19-ad46-4662-9612-4ee11150e274)

Note in the screenshot above that the first "CKEditor" entry (the warning) is provided by this contrib module, whereas the second one (the info) is provided by core (v4).

However, heading to `admin/config/content/formats` showed that the "Filtered HTML" format is configured with CKEditor (v4, but still, this is confusing).

PS: why do we have that information be a warning in the status page? Aren't there any legitimate use cases where people might not want or need any rich text editing configured on their site? It feels like the note that this module is adding should be added to the existing "CKEditor" entry on that page, which core provides (and also adding the version number for v5 of the editor).

**Comment by klonos** [comment]
...perhaps the easiest solution here would be to add the version to the sentense. So change this:

> CKEditor is installed but not enabled on any formats. ...

...to this instead:

> CKEditor 5 is installed but not enabled on any formats. ...

**Comment by indigoxela** [comment]
A PR is available, which clarifies the text.

**Comment by quicksketch** [comment]
Thanks, PR merged @indigoxela!

**Comment by quicksketch** [comment]
Related core issue to convert "CKEditor" to "CKEditor 4": https://github.com/backdrop/backdrop-issues/issues/6250
