### ISSUE TITLE
Image Alignment (data-align) support

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/ckeditor5#53]
Images should be able to be aligned left/right/center using either the main toolbar (if possible) and also the balloon toolbar. See https://ckeditor.com/docs/ckeditor5/latest/features/images/images-styles.html

![image](https://github.com/backdrop-contrib/ckeditor5/assets/100206/b85a23b8-79a9-41c7-9edc-24169abcd76b)

**Comment by quicksketch** [comment]
I filed a PR at https://github.com/backdrop-contrib/ckeditor5/pull/55. Surprisingly, all the JavaScript in `backdrop-image.js` was left entirely untouched. The only changes necessary were to pass in the expected configuration.

**Comment by quicksketch** [comment]
I merged the PR at #55 so that I can work on image caption (https://github.com/backdrop-contrib/ckeditor5/issues/56) and link (https://github.com/backdrop-contrib/ckeditor5/issues/54) support.

**Comment by indigoxela** [comment]
... and it works! :tada:

However, not sure if that's new, but changing the image doesn't actually change the src attribute value, but only the data-file-id (after saving). Needs more testing...

**Comment by quicksketch** [comment]
Ah, thanks! That's probably because replacing an image isn't possible in
Drupal so the plugin didn't support that use case. I'll take a look.
