### ISSUE TITLE
Ability to Link Images

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/ckeditor5#54]
Images should support being linked, and that link should be editable with the Backdrop link dialog just a text link.

See https://ckeditor.com/docs/ckeditor5/latest/features/images/images-linking.html

![image](https://github.com/backdrop-contrib/ckeditor5/assets/100206/5496f754-dc79-4192-8b90-5e47d101980a)

**Comment by quicksketch** [comment]
I have an initial PR working to enable linking image support, but I discovered the module from which we based link handling does not support link attributes beyond `href` on image links. See https://www.drupal.org/project/editor_advanced_link/issues/3349389

I believe that the starting point for image link attributes is that we need to add tracking for the `htmlLinkAttributes` attribute on `imageBlock` elements. There are also issues in that just manually adding attributes to link images in source mode are discarded (even with Generic HTML support enabled). So there are probably also issues with our upcast/downcast code.

**Comment by indigoxela** [comment]
Hm... I did get class, id, title and target attributes, though... for an *inline* image.
As soon as I toggle to something that wraps the image in a figure element, the attribs are gone.

So:

a > span > img - attributes applied and saved

But:

figure > a > img - nope, attributes stripped

**Comment by quicksketch** [comment]
Thanks @indigoxela, I did not try that. By "applied" do you mean that you used the dialog to add the attributes? Or that if they were in the source code they managed to stay intact when toggling between source mode and edit mode?

**Comment by indigoxela** [comment]
> By "applied" do you mean that you used the dialog to add the attributes?

Yes, exactly. I didn't even test with switching to source mode, only the "regular" way via dialog.

**Comment by indigoxela** [comment]
Did some more testing... funny, on images with caption turned on (so inside figure), the link *with* additional attribs gets wrapped around the caption. (Only type imageBlock).

Which makes me think, there's some parent/child mess somewhere, but ... I can't find where that might happen.

To reproduce that, add an image, turn on caption, add caption text, link the image (with attribs).

I end up with:

figure > a (without attribs besides href) > img | imagecaption > a (with all attribs besides href, wrapped around text)

No additional steps, only linking the image produces that.

**Comment by quicksketch** [comment]
@indigoxela I updated https://github.com/backdrop-contrib/ckeditor5/pull/67 with an additional commit that should make other attributes work on linked images. Could you give it a spin?

Turns out upcast/downcast code was pretty much all okay. The real missing part was that we needed to set the single `htmlLinkAttributes` attribute on the image model if the link is around an image, rather than setting/getting values from the link (which gets "absorbed" into the image model on upcast).

**Comment by indigoxela** [comment]
That's great! Well, ... almost. :wink: 

I can confirm, that linking an image now works *with* link attributes like class, id...
However, when opening such content with a linked image with caption turned on (after saving), the figcaption still gets wrapped in a link. This time additionally to the link wrapped around the image. And this time the figcaption link has no attributes.
So, somewhere in the upcast (I guess) there's still an unnecessary step? It doesn't seem to be caused by upcastImageBlockLinkGhsAttributes, though.

But this is yet another big step forward. :+1:

**Comment by quicksketch** [comment]
I cannot figure this one out. Here's a full set of steps to reproduce:

- Create a new node with CKEditor 5 as the editor.
- Insert an image.
- Enable the caption and enter caption text.
- Link the image to `/home`.
- Save the node.
- On view, everything works correctly.
- Edit the node.
- Upon CKEditor loading, the caption is now linked to `/home`, separate from the image, which is also linked to `/home`.

There are some other funky situations:

- If the caption is _already_ a link, then it is left alone.
- If part of the caption is already a link, then that link is left intact, but the rest of the caption gets wrapped in a link that duplicates the image link.

As far as I can tell, this is not an issue with our upcast code in `viewImageToModelImage()`, which seems to have everything correct. But a later converter is causing the caption to be wrapped in the image's link during upcast.

**Comment by quicksketch** [comment]
I reproduced this problem in Drupal as well. I created an issue at https://www.drupal.org/project/drupal/issues/3396483.

I think for this particular problem, we might want to go ahead and merge what we have and separate out this problem into its own issue, since it seems difficult to fix and a little bit of an edge-case compared to being able to link images at all.

**Comment by indigoxela** [comment]
Wow, didn't check Drupal for that. So it might even be a bug (regression) in CKE5, only triggered by Drupal/Backdrop caption handling?

I'm also unable to figure out, what's causing it. To debug I turned off plugins one by one (via ckeditor5.js), but didn't get any further. :disappointed:

Yeah, let's proceed with what we have now - step by step.

**Comment by quicksketch** [comment]
Great, well I've merged https://github.com/backdrop-contrib/ckeditor5/issues/54 and opened https://github.com/backdrop-contrib/ckeditor5/issues/69.
