### ISSUE TITLE
Image Caption (data-caption) Support

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/ckeditor5#56]
CKEditor 4 used the `data-caption` attribute to apply captions to `<img>` tags, which were then rendered as `<figure>` and `<figcaption>` elements. The current `backdrop-image.js` plugin has initial support for this too but it's not integrated into Backdrop yet.

**Comment by quicksketch** [comment]
@indigoxela I did a lot of fixing regarding both image caption and image alignment in https://github.com/backdrop-contrib/ckeditor5/pull/58. If you can generally check caption and alignment functionality that would be appreciated.

**Comment by indigoxela** [comment]
Excellent, we have captions!

I can confirm that captions work, both, by toggling via balloon toolbar and Backdrop dialog.

And captions also work with content created with v4 and when toggling between 4 and 5. :+1:
