### ISSUE TITLE
Changing an image has only temporary effect

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/ckeditor5#57]
When testing for #53, I realized that changing an image doesn't work, yet.

After picking a different one from the library, the new image appears in the editor, but the meta data in the wrapping span don't seem to get updated, which results in the old image (with the wrong file-id) showing up after saving.

![attribs-out-of-sync](https://github.com/backdrop-contrib/ckeditor5/assets/842066/f5818676-0525-42a9-9821-33a37835c449)

Could this be a problem with upcast/downcast?

**Comment by quicksketch** [comment]
Thanks for separating out this issue. This might be related to the downcast (converting the CKEditor internal model to the `<img>` tag), but it also looks like our `BackdropImageCommand::saveCallback()` method isn't doing anything with the returned `src` value, so the model isn't getting updated on dialog save in the first place. I'll look into this soon.

**Comment by indigoxela** [comment]
Seems like that problem's solved in the latest CKE version, but we have a new one: aspect ratio (style attribute) of images isn't updated, which leads to squeezed images after changing. Probably for similar reasons, though.

**Comment by quicksketch** [comment]
I tried out our latest in `1.x-1.x` and even with CKEditor 40.0.0 I'm seeing the original reported behavior: The image is updated in the editor but not when saving (or in source mode). And yes, we now have a new problem with resizing and inline styles being used by CKEditor, but at least we have height/width attributes!

**Comment by indigoxela** [comment]
I think, after the latest changes in CKE5, the width and height attribute should go directly to the image ... as number - no "px" attached.

Before that, it was necessary to workaround the fact, that CKE5 refused to handle these attributes, but that doesn't seem to be the case anymore. (Not sure, though.)

I'm also not sure, where the style attribute for aspect ratio should go now.

Another finding (you're probably aware of): currently the data-file-id attribute is a bit fragile. It's lost after opening the node form again. It does work, when initially inserting an image.

And, yes, the problem with outdated image src is still there (or back).

**Comment by indigoxela** [comment]
Some odd experiments here, but maybe useful info: If I generously comment out large parts in backdrop-image.js, all of a sudden width and height get set, when opening the form with an existing image. And even changing the image works.

Maybe the plugin currently does too much?

**Comment by quicksketch** [comment]
Yeah I think it's possible that we'll need to either remove or rework `modelImageHeightToAttribute` and `modelImageWidthToAttribute`. I'm taking a look at this issue today.

**Comment by quicksketch** [comment]
I filed https://github.com/backdrop-contrib/ckeditor5/issues/63 to fix image resizing. I'm still stumped on the changing image. I'd be really curious if you could manage commenting out sections of code again and identify which code is causing the problem.

**Comment by quicksketch** [comment]
I think I found the main problem, though I don't understand exactly how it works. I was looking in the downcast code everywhere, but the problem appeared to be in the upcast code. I guess you need to tell CKEditor on upcast which attributes are changeable in the model? I'm not sure. I figured it out initially by commenting out the downcast code, which did not work, then tried the upcast code, which had the right effect. Perhaps there's other things in upcast we can clean-up or remove and let CKEditor handle natively instead.

But in the mean time, I filed a PR at https://github.com/backdrop-contrib/ckeditor5/pull/65 that resolves the main problem of the src attribute not getting saved on changes.

**Comment by indigoxela** [comment]
Brilliant, that's a huge step forward!

I can confirm that changing the image now works correctly. :+1: 
And data-file-id seems to work again, too (it changes according to file).
There are remaining tasks with image dimension/aspect ratio, but those can get handled in a follow-up.

Yeah, some of the CKE concepts just aren't documented in a comprehensive way, so a lot is just trial and error. :disappointed: But we're on a good way now.

**Comment by quicksketch** [comment]
I looked into trying to inherit the conversion from CKEditor core, but it doesn't _seem_ as though it's possible in the case of images to let it pass through to CKEditor core. Since this solves our particular problem, let's leave the code in-place for now and just include that one fix. I merged it into 1.x-1.x. Thanks for the review and help here @indigoxela!
