### ISSUE TITLE
Update CKEditor to v40.0.0, update build documentation

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/ckeditor5#59]
Version 40.0.0 brings several bugfixes we'll benefit from.

For now we use a simplified update approach, which does require `npm`, but no advanced steps.

Creating a custom webpack build workflow, which also collects plugin translations and provides a functional map file should get handled in a follow-up.

**Comment by indigoxela** [comment]
Here's the update: https://github.com/backdrop-contrib/ckeditor5/pull/60

To "build" it, I used a totally simplified approach:

<details><summary>concat-build.sh</summary>

```
#!/bin/bash

npm install --save ckeditor5 \
  @ckeditor/ckeditor5-alignment \
  @ckeditor/ckeditor5-autoformat \
  @ckeditor/ckeditor5-basic-styles \
  @ckeditor/ckeditor5-block-quote \
  @ckeditor/ckeditor5-code-block \
  @ckeditor/ckeditor5-editor-classic \
  @ckeditor/ckeditor5-essentials \
  @ckeditor/ckeditor5-heading \
  @ckeditor/ckeditor5-horizontal-line \
  @ckeditor/ckeditor5-html-support \
  @ckeditor/ckeditor5-image \
  @ckeditor/ckeditor5-indent \
  @ckeditor/ckeditor5-language \
  @ckeditor/ckeditor5-link \
  @ckeditor/ckeditor5-list \
  @ckeditor/ckeditor5-paste-from-office \
  @ckeditor/ckeditor5-remove-format \
  @ckeditor/ckeditor5-source-editing \
  @ckeditor/ckeditor5-special-characters \
  @ckeditor/ckeditor5-style \
  @ckeditor/ckeditor5-table

cp node_modules/ckeditor5/build/ckeditor5-dll.js .

cat node_modules/@ckeditor/ckeditor5-*/build/*js >> ckeditor5-dll.js
```

</details>

Neither translations nor map file get updated that way, but that didn't happen either, with the [currently documented](https://github.com/backdrop-contrib/ckeditor5/blob/1.x-1.x/lib/UPGRADING.md) approach.

I also switched the name (from ckeditor.js to ckeditor5-dll.js).

And: yay :tada: with this version we now have width and height attributes on images.

**Comment by quicksketch** [comment]
Brilliant. Great work @indigoxela. So much less tedious than my initial attempt. Could you go ahead and add the `concat-build.sh` script to the repository for now, and update the documentation? I think webpack is probably our long-term solution but this certainly makes things better than before.

**Comment by indigoxela** [comment]
> go ahead and add the concat-build.sh script to the repository for now, and update the documentation

Sure, done. You ask me to write documentation? I did my very best. :grinning:

**Comment by quicksketch** [comment]
This is great! I'm excited to try it out.
