### ISSUE TITLE
Provide an option for enabling/disabling Autoformat(?)

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/ckeditor5#6]
I've bundled the [CKEditor 5 Autoformat plugin](https://ckeditor.com/docs/ckeditor5/latest/features/autoformat.html) and enabled it by default. This allows markdown-like keyboard shortcuts, like starting a line with an asterisk or dash immediately converts it to a bulleted list.

I'm not sure if this should be an option or not. Drupal 10 decided to just enable it all the time. I'm in favor of it because this same markdown syntax is supported on Google Docs, Dropbox Paper, and probably other systems (Office 365, maybe?) It seems like it's become more of a standard and it should possibly just always be there. Open to suggestions.

**Comment by klonos** [comment]
> ...this same markdown syntax is supported on Google Docs, Dropbox Paper, and probably other systems...

And places like GitHub/GitLab comments as well.

> ... It seems like it's become more of a standard and it should possibly just always be there. Open to suggestions.

I agree with the default being set to be on OOTB 👍🏼  ...however, there may be cases where content editors have been trained and for years might have been using those "triggers" (asterisk or dash followed by space etc.) for something else, to the point where it has become muscle memory. In such cases, it'll be desirable for site admins to be able to disable this "annoying" auto-complete.

**Comment by quicksketch** [comment]
I'm leaning towards leaving this as an always-on option for the time being. Seems markdown-like syntax is only becoming more popular, and it's uncommon to accidentally trigger it (although I do occasionally hit it with typing words that start with an underscore, but again that's developer-oriented). If a conversion is unwanted, you can also use Command + Z to undo the markdown conversion and leave the original text in place.

**Comment by indigoxela** [comment]
> Seems markdown-like syntax is only becoming more popular

I'm sharing that impression. For example, TinyMCE also ships with it (fully configurable by an option, though). And I've seen similar concepts in other WYSIWYG editors.

Maybe wait for some feedback here?

**Comment by argiepiano** [comment]
I like the feature and would also leave it on OOTB.

**Comment by herbdool** [comment]
I think it's good to leave it enabled.

**Comment by quicksketch** [comment]
Let's close this for the time being. I still like having it on all the time.
