### ISSUE TITLE
Resizing an Image after changing its src uses the previous image's aspect ratio

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/ckeditor5#66]
To reproduce:

- Insert a new image into a CKEditor 5 instance.
- Resize the image with drag handles.
- Edit the image using the Backdrop modal.
- Upload or select a different image that has different dimensions.
- Try to resize the image again, it will snap to the aspect ratio of the previous image.

**Comment by quicksketch** [comment]
This appears to be a CKEditor core bug: https://github.com/ckeditor/ckeditor5/issues/15179

**Comment by indigoxela** [comment]
Maybe related: when updating an image - without ever touching the resize handle - the image width/height stay empty.

When inserting an image (selected from library) for the first time, dimensions are set.

**Comment by quicksketch** [comment]
Nice spotting. I think the empty width/height are caused by our own code when the dialog saves an image, it specifically uses `setAttribute()` with an empty string. I think if we used `removeAttribute()` on empty strings, CKEditor might auto-populate the width/height? There's also [setImageNaturalSizeAttributes](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imageutils-ImageUtils.html#function-setImageNaturalSizeAttributes) new in v40 that we can use if it needs to be executed manually.

**Comment by quicksketch** [comment]
I filed a PR at https://github.com/backdrop-contrib/ckeditor5/pull/101 that should fully fix setting width/height attributes. I think it covers all problematic scenarios, including the original report and if width/height are left empty, the "natural" image dimensions are populated both as attributes and in the modal dialog.

**Comment by indigoxela** [comment]
Brilliant, the problem's fixed now. No more squeezed images, and they all get their dimensions set when inserting from image browser. :+1:

**Comment by quicksketch** [comment]
Thanks for validating @indigoxela! I merged the PR.
