### ISSUE TITLE
Image Captions Do Not Support Nested Tags like `<a>` or `<strong>`

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/ckeditor5#68]
When inserting an image with a caption, CKEditor 5 let's you modify the caption to include links, bold, italic, etc. But when saving the content, it seems to get corrupted somehow. On output the content is mangled.

Image with caption with bold text:

![image](https://github.com/backdrop-contrib/ckeditor5/assets/100206/6d9fd36a-c12b-4903-ade6-a188101131de)

On output:

![image](https://github.com/backdrop-contrib/ckeditor5/assets/100206/9662a7bf-0d7e-43cd-a5c8-f4ffebfef2af)

In the database, this is the markup being saved:

```
<img data-file-id="1" alt="" src="/files/field/image/card1-layout_7.png" width="260" height="173" data-align="center" data-caption="Caption <strong>content</strong> here">
```

The contents of the `data-caption` field should be HTML entity escaped, that's probably the source of the problem.

**Comment by indigoxela** [comment]
OK, this one seems fixable, though. Looking at the result of node_load:

```
   'body' => 
  array (
    'und' => 
    array (
      0 => 
      array (
        'value' => '<img src="/files/field/image/card1-layout.png" data-file-id="1" alt="" data-caption="My <strong>caption</strong> tada" width="800" height="533">',
        'summary' => '',
        'format' => 'filtered_html_cke5',
        'safe_value' => '<img src="/files/field/image/card1-layout.png" data-file-id="1" alt="">caption</strong> tada" width="800" height="533"&gt;',
        'safe_summary' => '',
      ),
    ),
  ),
```

^^ The attribute value isn't encoded (e.g. lt/gt). CKE doesn't seem to take care of value encoding (anymore)?

If I switch to CKE4 in that node form and save, the value gets:

```
   'body' => 
  array (
    'und' => 
    array (
      0 => 
      array (
        'value' => '<img alt="" data-caption="My &lt;strong&gt;caption&lt;/strong&gt; tada" data-file-id="1" height="533" src="/files/field/image/card1-layout.png" width="800" />',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<figure class="caption caption-img"><img alt="" data-file-id="1" height="533" src="/files/field/image/card1-layout.png" width="800" /><figcaption>My <strong>caption</strong> tada</figcaption></figure>',
        'safe_summary' => '',
      ),
    ),
```

**Comment by indigoxela** [comment]
Incredible... I know [where things happen](https://github.com/backdrop-contrib/ckeditor5/blob/1.x-1.x/js/plugins/backdrop-image/backdrop-image.js#L408), the only thing I'd need is a method to convert to an encoded string _instead_ of full HTML content... and I'm not able to figure out, how. :shrug: I could use js-native dom handling, but then the ampersand gets double encoded (`&amp;lt;` - by CKE).

**Comment by quicksketch** [comment]
Yeah, I looked into the problem and found the same thing. What weird quirk of JavaScript to not have an escape function. And things get weirder, I tried just replacing `<` and `>` but then they became double-escaped like you saw. I added the following:

```
let captionText = editor.data.processor.toData(viewDocumentFragment);
captionText = captionText.replace('<', '&lt;`).replace('>', '&gt;');
```

But instead of the expected output:
```
My &lt;strong&gt;caption&lt;/strong&gt; tada
```

The output became double-escaped:
```
My &amp;lt;strong&amp;gt;caption&amp;lt;/strong&amp;gt; tada
```

This particular behavior does seem Backdrop-specific (not reproduceable in Drupal), so it's either our code or an issue with CKEditor v40.

**Comment by indigoxela** [comment]
It's CKEditor. I verified with a vanilla setup (Classic editor), without Backdrop involved, only with bare HTML and CKE v 40.0.0 from cdn.

**Comment by indigoxela** [comment]
We might end up with a request for a core change...

Some background:

Drupal's not affected by this, as their Filter module seems to support `<` and `>` in attributes. At least, they're [testing for that](https://git.drupalcode.org/project/drupal/-/blob/11.x/core/modules/filter/tests/src/Kernel/FilterKernelTest.php?ref_type=heads#L167).

CKEditor seems to use some sort of `JSON.stringify()` for attributes in their [AttributeOperation class](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-engine/src/model/operation/attributeoperation.ts). This doesn't actually explain double encoding (ampersand), but at least explains, why they don't encode to lt/gt by default.

*Is* unencoded markup allowed in data attributes - yes or no? Well, I can't reliably answer. Maybe, maybe not.

What we do know: the Filter module in BackdropCMS doesn't handle that. That's why markup breaks on display. Note: it does work, as long as the "Convert image captions..." filter runs before "Limit allowed HTML tags". But that's no real solution.

**Comment by quicksketch** [comment]
> Drupal's not affected by this, as their Filter module seems to support < and > in attributes. At least, they're [testing for that](https://git.drupalcode.org/project/drupal/-/blob/11.x/core/modules/filter/tests/src/Kernel/FilterKernelTest.php?ref_type=heads#L167).

Thanks for digging that up. I would not expect that to be supported. I wonder if that's what's making Drupal's captions work with CKEditor? The code comments say they're to cover users manually entering the captions in source mode, but that seems like an exceptional situation.

> Is unencoded markup allowed in data attributes - yes or no?

By the HTML specification, all attribute values should be entity encoded. Rather than adding support for invalid markup to the filter, I'd prefer to make CKEditor 5 output valid HTML for the caption attributes.

**Comment by indigoxela** [comment]
>  I wonder if that's what's making Drupal's captions work with CKEditor?

I don't think so, no. Looking at D9 (currently have no D11), it seems like they manage to prevent the double encoding. Not sure, how. There's a lot of code involved to set attributes.

**Comment by indigoxela** [comment]
My current suspicion: the converter priority only sets the order, but doesn't replace the original converter, so another one runs after viewCaptionToCaptionAttribute, which causes the double encoding.
But that's just wild guessing.

**Comment by quicksketch** [comment]
I found that the source of the problem is that CKEditor 5 is acting "normally" in that `<` and `>` characters apparently _are_ allowed (but discouraged) by the HTML5 specification.

Drupal went through this same issue in https://www.drupal.org/project/ckeditor5/issues/3247246 and that's what the `drupalHtmlEngine` plugin does in their CKEditor 5 module. I had largely ignored that plugin because I did not know what it was doing. Now we know that it is to solve this exact problem with `data-caption` attributes.

Drupal also has an issue to update their filtering system to fully support unescaped `<` and `>` symbols at https://www.drupal.org/project/drupal/issues/3227831. But I'm inclined to fix this in CKEditor module, which really should be escaping these symbols as a best-practice.

Unfortunately that means we need to include another out-of-the-box plugin.

**Comment by quicksketch** [comment]
A little more background research that I found helpful:

[This StackOverflow post on why `<` and `>` characters aren't escaped by JavaScript](https://stackoverflow.com/questions/18059087/innerhtml-for-character-reference-in-attribute-value-is-not-preserved-as-escaped)

That post is relevant because CKEditor exports HTML pretty much just by asking the browser for the `.innerHTML` attribute:

```
const container = doc.createElement('div');
container.appendChild(fragment);
return container.innerHTML;
```

See the code for [basichtmlwriter.ts](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-engine/src/dataprocessor/basichtmlwriter.ts) for more.

So CKEditor delegates the task of exporting the HTML from the DOM to source code to the browser. Interestingly, that means that you might get a different HTML source depending on what browser you use.

Separately, there's a discussion going on at https://github.com/whatwg/html/issues/6235 to recommend that attribute characters `<` and `>` start being escaped when serialized, and apparently that change has already been made in the bleeding edge version of Chrome. So eventually it's possible that this problem would have solved itself, but I don't think we can wait for browsers, and I just generally don't like that simply loading CKEditor on a piece of content might change its output between different browsers. Since `.innerHTML` is not standardized, there's no guarantee other changes wouldn't also happen beyond just the problem we're seeing with unescaped characters.

IMO, this is an upstream problem that should be solved by CKEditor, but again I don't think we should necessarily wait on them to implement such a change. I have not yet been able to find an upstream issue describing this problem.

**Comment by quicksketch** [comment]
Filed an upstream issue with CKEditor here: https://github.com/ckeditor/ckeditor5/issues/15293

**Comment by indigoxela** [comment]
Wow, many thanks for your thorough research.
Yet another rabbit hole for us in this integration, though.

**Comment by quicksketch** [comment]
> Yet another rabbit hole for us in this integration, though.

Yes. Lots of those with CKEditor it seems. :roll_eyes:

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop-contrib/ckeditor5/pull/88.

**Comment by indigoxela** [comment]
Excellent! I can confirm that markup in image captions now works (em, strong...) and tags get escaped properly in the attribute. :tada: - Regardless of the filter order.

**Comment by quicksketch** [comment]
Thanks @indigoxela. I fixed test failures and merged that PR.

The initial response to the upstream issue isn't very positive, so I doubt that will make progress soon. But maybe? It's probably best that we have an solution for now, but it may become permanent.

**Comment by indigoxela** [comment]
>  It's probably best that we have an solution for now, but it may become permanent.

I read their response and agree - we need a consistent solution now, waiting for a standard and client implementations isn't a option at this point. And, yes, I guess, it might become permanent.
