### ISSUE TITLE
Remove ckeditor5.compat.js

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/ckeditor5#70]
I believe we no longer need the `ckeditor5.compat.js` file now that we renamed `ckeditor.js` to `ckeditor-dll.js` (in https://github.com/backdrop-contrib/ckeditor5/issues/59). Is that right @indigoxela?

The file was previously used to help CKEditor 4 not get confused by two `ckeditor.js` files present on the page at the same time.

**Comment by quicksketch** [comment]
Actually maybe it will be useful to keep around for a different purpose, like I used in https://github.com/backdrop-contrib/ckeditor5/pull/71. But that PR still removes the current work-around, which I believe is safe to take out now.

**Comment by indigoxela** [comment]
I confirmed that this workaround is no longer necessary. We can remove or repurpose as needed. :+1:

**Comment by indigoxela** [comment]
I think, we can close this one, as the file is used in a different way now.
