### ISSUE TITLE
Small regression with ckeditor5.compat.js

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/ckeditor5#78]
In https://github.com/backdrop-contrib/ckeditor5/commit/31539bce6189b0e8a26646c408f42b5ff094abbc we introduced a workaround to prevent conflicts with CKEditor 4.

However, this causes a problem, if CKEditor 4 isn't available at all (not attached to any format):

```
Uncaught ReferenceError: CKEDITOR is not defined
```
Easy to fix, though.

**Comment by quicksketch** [comment]
Super, thanks @indigoxela!
