### ISSUE TITLE
Add Telemetry Info

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/ckeditor5#84]
We need to start reporting CKEditor version from this module, as well as whether sites are running both CKEditor 4 and 5 at the same time. See the core issue at https://github.com/backdrop/backdrop-issues/issues/6214 for an overall plan.

**Comment by quicksketch** [comment]
Looking at what was added to core, we're currently reporting the entire CKEditor version number to Telemetry (i.e. `4.18.0`). But on https://backdropcms.org/project/backdrop/telemetry, the Telemetry settings page is configured to only show the major version number (i.e. `4`).

I think that doesn't quite line up with what we want Telemetry to report. The new versions of CKEditor are incrementing major version numbers, currently on `40.0.0` (prior to that was `39.0.0`, `38.0.2`, etc). So CKEditor 5 will be these high numbers while 3 was always within the `3.x.y` space.

Reporting the library version only, we'll either end up with a consolidated list of versions that mix CKEditor 4 and 5 versions like this:

![image](https://github.com/backdrop-contrib/ckeditor5/assets/100206/86781027-fd3b-443b-9545-a94861f64ca2)

Or two separate sets of numbers, one for each CKEditor 4 and 5:

![image](https://github.com/backdrop-contrib/ckeditor5/assets/100206/b1598303-288b-457f-8a56-dfae21c98a2d)

But I think the most valuable metric we're looking for is whether sites are running CKEditor 4 _module_ vs CKEditor 5 _module_. The library version isn't so important. Put into a chart it would look like this:

![image](https://github.com/backdrop-contrib/ckeditor5/assets/100206/3c335b04-a5b4-4a88-a868-92091cffe2ad)

One of the troubles here is the "both" item. Telemetry doesn't support combining quantities before showing values. Also if a site has both CKEditor 4 and 5, it shouldn't report as 4 or 5, but as "both". I don't think we realized that reporting "both" would require altering the data between modules.

**Comment by quicksketch** [comment]
Also, it occurs to me that maybe we should take into account TinyMCE module and possibly even BUEditor. In which case what we're looking at might be tracking overall editors with `hook_editor_info()`, rather than specifically CKEditor.

**Comment by indigoxela** [comment]
I think, it's fine to only take into account, which editor modules are enabled, hook_editor_info seems fine, maybe filter_get_editors(). There can be several per site, any combination.

I wonder, though, if this will provide enough info to evaluate, at which point CK4 gets obsolete. But we probably can't rip it out of core before 2.x, right?

I think, as the libraries are module-provided, the exact versions (e.g. 40.0.0 vs. 38.0.2) aren't that useful for our case.

**Comment by quicksketch** [comment]
I chatted with @jenlampton on this topic and I think we potentially might want all the following (least to most important):

1. Have `telemetry_telemetry_info()` provide CKEditor 4/5/both data based on `module_exists()` for each module.
2. Have `filter_telemetry_info()` provide information based on all editors in use.
3. Have `ckeditor5_telemetry_info()` provide CKEditor 5 library version.

So that means for this contrib module, only the last (and least important) item can be implemented here.

**Comment by quicksketch** [comment]
PR at https://github.com/backdrop-contrib/ckeditor5/pull/93 is pretty simple. CKEditor 5 version now shows as a separate Telemetry item:

![image](https://github.com/backdrop-contrib/ckeditor5/assets/100206/d492af60-659e-40c7-ac14-4f57e3203778)

**Comment by quicksketch** [comment]
I'll open core issues for remaining Telemetry items. I merged https://github.com/backdrop-contrib/ckeditor5/pull/93 into 1.x-1.x.
