### ISSUE TITLE
Admin form item missing when editing CKE5 enabled format settings

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/ckeditor5#85]
Not sure, when this broke, but when opening the format settings for formats with CKE5 already enabled, the form items for "File uploading" are missing, for "Style list" not even the vertical tab shows up.

Both form parts are available when creating a new format.

When switching to CKE4, on such an existing format, then back to CKE5, the form item (checkbox) for "File uploading" is back, the vertical tab for "Style list" still won't show up. Refreshing the page - form item gone again. :thinking: 

![form-items-missing](https://github.com/backdrop-contrib/ckeditor5/assets/842066/3a3ed647-7f14-4aab-8c66-ba6dc34730a8)

**Comment by indigoxela** [comment]
The solution's quite obvious... well, sort of. Partly...

The style settings disappear, if the "styles" toolbar item isn't selected. Dragging that into the toolbar enables the form items below (with vertical tab). A bit odd, but probably expected behavior.

The link plugin's currently undergoing some rewrite, and that's probably why the form item doesn't even appear, when the link toolbar item is active (which it isn't in above screenshot).

So the "File uploading" form part's really currently broken.

**Comment by indigoxela** [comment]
Here's a [one-liner fix](https://github.com/backdrop-contrib/ckeditor5/pull/87) - backdropLink's now a standalone plugin, we no longer use the default "link" plugin.

It's still a bit odd, that one of the vertical tab items remains, while the other doesn't.

**Comment by quicksketch** [comment]
> The style settings disappear, if the "styles" toolbar item isn't selected. Dragging that into the toolbar enables the form items below (with vertical tab). A bit odd, but probably expected behavior.

@klonos thought that was a weird behavior too. There's a separate issue at https://github.com/backdrop-contrib/ckeditor5/issues/14.

I merged https://github.com/backdrop-contrib/ckeditor5/issues/85 to solve the problem with the file upload settings in particular. Thanks @indigoxela!
