### ISSUE TITLE
Images: pasting fails when a dimension limit is set

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/ckeditor5#95]
Yes, images again...

To reproduce:

- enable image uploads (if not done yet)
- limit dimensions (width/height)
- paste / drop a _larger_ image into the editor

A browser popup (alert) shows the notification, that the image has been resized. 
`The image was resized to fit within the maximum allowed dimensions of <em class="placeholder">500x500</em> pixels.` (Also note the sanitized markup.)

Behind an overlay the pasted image is visible in editor content.

Clicking "OK" in the notification **removes** the image from content.

Checking /admin/content/files shows that the image has been uploaded, but not resized, the file is in "temporary" state.

This only happens when pasting / dropping, of course. Not when using the dialog.

Screenshot:

![dialog on overlay](https://github.com/backdrop-contrib/ckeditor5/assets/842066/90a650a1-b1b5-4246-a208-b5bfe156a13d)

**Comment by indigoxela** [comment]
OK, got it...

In js/plugins/backdrop-image/backdrop-image.js there's a check if there are "errors" in response. Which is also the case when an image is resized, but then uploaded is `1`.

Example from console.log:
```
{
  "uploaded": 1,
  "fileName": "dog-scratching-2776225_960_720.png",
  "url": "/files/inline-images/dog-scratching-2776225_960_720.png",
  "fileId": "194",
  "width": 353,
  "height": 500,
  "error": {
    "message": "The image was resized to fit within the maximum allowed dimensions of <em class=\"placeholder\">500x500</em> pixels. "
  }
}
```
So it's unreliable to [reject](https://github.com/backdrop-contrib/ckeditor5/blob/1.x-1.x/js/plugins/backdrop-image/backdrop-image.js#L1006) already, when there's a message. It might not be a fatal one.

**Comment by indigoxela** [comment]
Another hour lost to figure out, how notifcations might work in CKE5. Gave up now and simply stick with alert().

#96 fixes resized images - they're no longer rejected (removed), but get uploaded, resized and their dimensions updated inside the editor. (That was the easy part.)

It seems like CKE5 doesn't actually provide any styled notifications anymore. We'd have to implement a custom solution, I guess. I belief, we had one here some time ago, but maybe I'm wrong or maybe it got removed when restructuring.

**Comment by indigoxela** [comment]
I think, we'd better split notifications out, as it might be a bigger task, that shouldn't block image resizing.

**Comment by quicksketch** [comment]
Thanks @indigoxela, this PR looks good. I tested it and it works to inform users of a resize while still accepting the image.

We might go ahead and start using CKEditor's notification system using the [`showWarning()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_notification_notification-Notification.html#function-showWarning) or [`showInfo()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_notification_notification-Notification.html#function-showInfo) methods, but it will result in the same behavior of calling `window.alert()` for the time being.

I'd be fine merging this PR as-is since it prevents the images from getting lost. And we can adjust the notification system usage in #97.

**Comment by quicksketch** [comment]
@indigoxela I pushed an additional commit to your PR at https://github.com/backdrop-contrib/ckeditor5/pull/96 to use CKEditor's notification system, even though right now it calls `window.alert()` and ultimately has identical behavior before and after my new commit. But if/when CKEditor gets better notifications, it will start using them right away.

**Comment by indigoxela** [comment]
> I pushed an additional commit to your PR at https://github.com/backdrop-contrib/ckeditor5/pull/96 to use CKEditor's notification system

Many thanks for your addition, that's a great step forward and it works. :+1:

**Comment by quicksketch** [comment]
With the separate issue for improving the notification at https://github.com/backdrop-contrib/ckeditor5/issues/97, this issue is completed. Thanks @indigoxela!
