### ISSUE TITLE
Update CKEditor to v40.1.0

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/ckeditor5#98]
A new release, and I think, if fixes at least one of the problems we're struggling with:

https://github.com/ckeditor/ckeditor5/releases/tag/v40.1.0

Or maybe not yet - the image ratio thing got slightly better, but isn't fixed.

image.insert.type seems relevant - 'auto' is what we want.

**Comment by quicksketch** [comment]
Thanks @indigoxela! Yeah the image ratio thing seems to have changed slightly. Let's continue that in https://github.com/backdrop-contrib/ckeditor5/issues/66.

> image.insert.type seems relevant - 'auto' is what we want.

I agree, I'll test what difference that makes.

**Comment by quicksketch** [comment]
If `image.insert.type` is `auto` or using CKEditor 40, inserting an image at the end of the first paragraph line you get this:

![image](https://github.com/backdrop-contrib/ckeditor5/assets/100206/cef8db99-3110-48b6-a594-e77a183ddbc1)


Now if `image.insert.type` is the new default (`block`) then inserting an image when the cursor is at the end of the first paragraph you get this:

![image](https://github.com/backdrop-contrib/ckeditor5/assets/100206/36776e61-e42d-4570-8536-4d6cad69cf27)

I actually think we should probably keep the new behavior. But perhaps we can discuss that issue separately. I think this general update is good for us to get in so we can address any other new oddities.

**Comment by indigoxela** [comment]
I'd actually suggest "auto", so it behaves like in v4, but don't have strong opinions re that.
